import { Translations, Language, UserTier, User, Product, AcademyResource } from './types';

export const TRANSLATIONS: Translations = {
  [Language.FR]: {
    login_title: "Espace Partenaire",
    login_subtitle: "Partenaire KRX Aesthetics",
    login_select_level: "Sélectionnez votre niveau d'accès",
    login_std_title: "STANDARD",
    login_std_subtitle: "Accès essentiel",
    login_std_price: "CHF 300/mois",
    login_std_features: "Commandes, Catalogue produits, Formation base",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Accès intégral",
    login_prem_price: "CHF 800/mois",
    login_prem_features: "Tout Standard, Tarifs préférentiels, Academy Elite, Support VIP, Insights business, Priorité stock",
    login_btn_access: "ACCÉDER",
    login_no_account: "Vous n'avez pas encore de compte ?",
    login_become_partner: "Devenir partenaire",
    login_back: "Retour",
    login_space_std: "Espace Standard",
    login_space_prem: "Espace Premium",
    login_id_label: "UTILISATEUR",
    login_id_label_prem: "UTILISATEUR PREMIUM",
    login_pwd_label: "MOT DE PASSE",
    login_secure_std: "Connexion sécurisée DermaKor",
    login_secure_prem: "Connexion sécurisée niveau Elite",

    login_btn: "Accéder au Portail",
    login_secure: "Connexion sécurisée par DermaKor Swiss",
    nav_dashboard: "Vue d'ensemble",
    nav_order: "Commande Pro",
    nav_academy: "DermaKor Academy",
    nav_logout: "Déconnexion",
    dash_welcome: "Bienvenue, Dr. ",
    dash_tier_status: "Statut Partenaire",
    dash_progress_title: "Objectif Mensuel",
    dash_min_goal: "Objectif minimum",
    dash_monthly_goal: "Objectif Mensuel",
    dash_active_tier_premium: "Membre Premium Actif",
    dash_current_spend: "Volume actuel",
    dash_recent_orders: "Dernières expéditions",
    dash_order_id: "Réf.",
    dash_date: "Date",
    dash_amount: "Montant",
    dash_status: "État",
    dash_view_all: "Voir tout",
    order_title: "Système de Commande",
    order_subtitle: "Sélectionnez vos produits professionnels pour l'institut.",
    order_col_product: "Référence Produit",
    order_col_price: "Prix Pro (CHF)",
    order_col_qty: "Quantité",
    order_col_total: "Total Ligne",
    order_summary: "Récapitulatif de commande",
    order_submit: "Valider la commande",
    academy_title: "Centre de Formation Professionnel",
    academy_subtitle: "Protocoles avancés et documentation technique.",
    academy_locked: "Réservé Premium",
    academy_view: "Consulter",
    common_premium_badge: "Membre Premium",
    common_standard_badge: "Membre Standard",

    // Admin Pricing
    pricing_title: "Gestion des Prix",
    pricing_subtitle: "Configuration des remises globales et individuelles",
    global_config: "Configuration Globale",
    apply_global: "Appliquer Remise Globale",
    save_changes: "Enregistrer les modifications",
    base_price: "Prix de Base",
    std_tier: "Tier Standard",
    prem_tier: "Tier Premium",
    final_price: "Prix Final",
    savings: "Économie",
    method: "Méthode",
    percentage: "Pourcentage (%)",
    fixed: "Prix Fixe (CHF)",
    history: "Historique"
  },
  [Language.DE]: {
    login_title: "Partnerbereich",
    login_subtitle: "KRX Aesthetics Partner",
    login_select_level: "Wählen Sie Ihre Zugangsebene",
    login_std_title: "STANDARD",
    login_std_subtitle: "Basiszugang",
    login_std_price: "CHF 300/Monat",
    login_std_features: "Bestellungen, Produktkatalog, Basisschulung",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Vollzugang",
    login_prem_price: "CHF 800/Monat",
    login_prem_features: "Alles Standard, Vorzugspreise, Academy Elite, VIP Support, Business Insights, Priorität Lager",
    login_btn_access: "ZUGANG",
    login_no_account: "Noch kein Konto?",
    login_become_partner: "Partner werden",
    login_back: "Zurück",
    login_space_std: "Standard Bereich",
    login_space_prem: "Premium Bereich",
    login_id_label: "BENUTZER",
    login_id_label_prem: "PREMIUM BENUTZER",
    login_pwd_label: "PASSWORT",
    login_secure_std: "Sichere Verbindung DermaKor",
    login_secure_prem: "Elite-Verbindung",

    login_btn: "Zum Portal",
    login_secure: "Gesicherte Verbindung durch DermaKor Swiss",
    nav_dashboard: "Übersicht",
    nav_order: "Bestellung",
    nav_academy: "DermaKor Akademie",
    nav_logout: "Abmelden",
    dash_welcome: "Willkommen, Dr. ",
    dash_tier_status: "Partnerstatus",
    dash_progress_title: "Monatsziel",
    dash_min_goal: "Mindestziel",
    dash_monthly_goal: "Monatsziel",
    dash_active_tier_premium: "Aktives Premium-Mitglied",
    dash_current_spend: "Aktuelles Volumen",
    dash_recent_orders: "Letzte Lieferungen",
    dash_order_id: "Ref.",
    dash_date: "Datum",
    dash_amount: "Betrag",
    dash_status: "Status",
    dash_view_all: "Alle ansehen",
    order_title: "Bestellsystem",
    order_subtitle: "Wählen Sie Ihre professionellen Produkte für das Institut.",
    order_col_product: "Produktreferenz",
    order_col_price: "Profi-Preis (CHF)",
    order_col_qty: "Menge",
    order_col_total: "Zeilensumme",
    order_summary: "Bestellübersicht",
    order_submit: "Bestellung bestätigen",
    academy_title: "Professionelles Ausbildungszentrum",
    academy_subtitle: "Fortgeschrittene Protokolle und technische Dokumentation.",
    academy_locked: "Premium Exklusiv",
    academy_view: "Ansehen",
    common_premium_badge: "Premium Mitglied",
    common_standard_badge: "Standard Mitglied",

    // Admin Pricing
    pricing_title: "Preisverwaltung",
    pricing_subtitle: "Konfiguration globaler und individueller Rabatte",
    global_config: "Globale Konfiguration",
    apply_global: "Globalen Rabatt anwenden",
    save_changes: "Änderungen speichern",
    base_price: "Basispreis",
    std_tier: "Standard Stufe",
    prem_tier: "Premium Stufe",
    final_price: "Endpreis",
    savings: "Ersparnis",
    method: "Methode",
    percentage: "Prozentsatz (%)",
    fixed: "Festpreis (CHF)",
    history: "Verlauf"
  },
  [Language.IT]: {
    login_title: "Area Partner",
    login_subtitle: "Partner KRX Aesthetics",
    login_select_level: "Seleziona il tuo livello di accesso",
    login_std_title: "STANDARD",
    login_std_subtitle: "Accesso essenziale",
    login_std_price: "CHF 300/mese",
    login_std_features: "Ordini, Catalogo prodotti, Formazione base",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Accesso integrale",
    login_prem_price: "CHF 800/mese",
    login_prem_features: "Tutto Standard, Prezzi preferenziali, Academy Elite, Supporto VIP, Approfondimenti business, Priorità stock",
    login_btn_access: "ACCEDI",
    login_no_account: "Non hai ancora un account?",
    login_become_partner: "Diventa partner",
    login_back: "Indietro",
    login_space_std: "Area Standard",
    login_space_prem: "Area Premium",
    login_id_label: "UTENTE",
    login_id_label_prem: "UTENTE PREMIUM",
    login_pwd_label: "PASSWORD",
    login_secure_std: "Connessione sicura DermaKor",
    login_secure_prem: "Connessione Elite",

    login_btn: "Accedi al Portale",
    login_secure: "Connessione sicura da DermaKor Swiss",
    nav_dashboard: "Panoramica",
    nav_order: "Ordini Pro",
    nav_academy: "Accademia DermaKor",
    nav_logout: "Esci",
    dash_welcome: "Benvenuto, Dr. ",
    dash_tier_status: "Stato Partner",
    dash_progress_title: "Obiettivo Mensile",
    dash_min_goal: "Obiettivo Minimo",
    dash_monthly_goal: "Obiettivo Mensile",
    dash_active_tier_premium: "Membro Premium Attivo",
    dash_current_spend: "Volume Attuale",
    dash_recent_orders: "Ultime Spedizioni",
    dash_order_id: "Rif.",
    dash_date: "Data",
    dash_amount: "Importo",
    dash_status: "Stato",
    dash_view_all: "Vedi tutto",
    order_title: "Sistema di Ordinazione",
    order_subtitle: "Seleziona i prodotti professionali per l'istituto.",
    order_col_product: "Riferimento Prodotto",
    order_col_price: "Prezzo Pro (CHF)",
    order_col_qty: "Quantità",
    order_col_total: "Totale Riga",
    order_summary: "Riepilogo Ordine",
    order_submit: "Conferma Ordine",
    academy_title: "Centro Formazione Professionale",
    academy_subtitle: "Protocolli avanzati e documentazione tecnica.",
    academy_locked: "Riservato Premium",
    academy_view: "Visualizza",
    common_premium_badge: "Membro Premium",
    common_standard_badge: "Membro Standard",

    // Admin Pricing
    pricing_title: "Gestione Prezzi",
    pricing_subtitle: "Configurazione sconti globali e individuali",
    global_config: "Configurazione Globale",
    apply_global: "Applica Sconto Globale",
    save_changes: "Salva modifiche",
    base_price: "Prezzo Base",
    std_tier: "Livello Standard",
    prem_tier: "Livello Premium",
    final_price: "Prezzo Finale",
    savings: "Risparmio",
    method: "Metodo",
    percentage: "Percentuale (%)",
    fixed: "Prezzo Fisso (CHF)",
    history: "Cronologia"
  }
};

export const MOCK_USER: User = {
  id: 'u123',
  name: 'Sophie Dubois',
  instituteName: 'Institut Esthétique Léman',
  tier: UserTier.STANDARD,
  currentSpend: 2150,
  monthlyGoal: 3000
};

export const PRODUCT_CATEGORIES = [
  "Tous les produits",
  "Gamme HomeCare",
  "Sérum",
  "Crème",
  "Tonique",
  "Démaquillant - Nettoyant",
  "Traitement Spécialisé",
  "Masque Concentré",
  "Meso Booster Ampoule",
  "Exfoliant",
  "Soin Peeling",
  "Gamme Pfect-A",
  "Solution HydraFacial",
  "Accessoire"
];

// Helper to init pricing
const withPricing = (prod: any) => ({
  ...prod,
  pricing: {
    basePrice: prod.price,
    standard: { type: 'PERCENTAGE', value: 0 },
    premium: { type: 'PERCENTAGE', value: 10 } // Default 10% premium discount for mock
  }
});

const RAW_PRODUCTS: Product[] = [
  // --- PEELING ---
  { id: 'biocell-bc1-aha-bha', sku: 'KRX-BC1', name: 'BioCell+ BC1 "AHA & BHA" - 300 ml', category: 'Peeling', price: 95.00, stockStatus: 'LOW_STOCK', description: 'Solution peeling AHA/BHA professionnelle.' },
  { id: 'pre-peel-toner', sku: 'KRX-PPT', name: 'Pre Peel Toner', category: 'Peeling', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Préparation essentielle avant peeling.' },
  { id: 'illumin-biphasic-peeling-solution', sku: 'KRX-IBPS', name: 'Illumin Biphasic Peeling Solution', category: 'Peeling', price: 120.00, stockStatus: 'IN_STOCK', description: 'Solution peeling biphasique illuminatrice.' },
  { id: 'blue-peel', sku: 'KRX-BLP', name: 'Blue Peel - 50 ml', category: 'Peeling', price: 85.00, stockStatus: 'LOW_STOCK', description: 'Peeling bleu intensif.' },
  { id: 'brightening-peel', sku: 'KRX-BRP', name: 'Brightening Peel', category: 'Peeling', price: 90.00, stockStatus: 'IN_STOCK', description: 'Peeling éclaircissant.' },
  { id: 'pre-peel-cleanser', sku: 'KRX-PPC', name: 'Pre Peel Cleanser', category: 'Peeling', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant préparatoire peeling.' },
  { id: 'post-peel-toner', sku: 'KRX-POT', name: 'Post Peel Toner', category: 'Peeling', price: 45.00, stockStatus: 'IN_STOCK', description: 'Tonique apaisant post-peeling.' },
  { id: 'glow-peel', sku: 'KRX-GLP', name: 'Glow Peel', category: 'Peeling', price: 95.00, stockStatus: 'IN_STOCK', description: 'Peeling éclat immédiat.' },
  { id: 'clear-peel', sku: 'KRX-CLP', name: 'Clear Peel', category: 'Peeling', price: 92.00, stockStatus: 'IN_STOCK', description: 'Peeling purifiant anti-imperfections.' },
  { id: 'green-sea-peel', sku: 'KRX-GSP', name: 'Green Sea Peel', category: 'Peeling', price: 130.00, stockStatus: 'IN_STOCK', description: 'Spicules marins bio-microneedling.' },
  { id: 'r3-therapeel', sku: 'KRX-R3T', name: 'R3 Therapeel', category: 'Peeling', price: 110.00, stockStatus: 'IN_STOCK', description: 'Peeling thérapeutique régénérant.' },
  { id: 'mela-pro-plus-cold-peel', sku: 'KRX-MPP', name: 'MelaPro Plus Cold Peel', category: 'Peeling', price: 140.00, stockStatus: 'IN_STOCK', description: 'Peeling froid dépigmentant.' },
  { id: 'lazer-peel', sku: 'KRX-LZP', name: 'LaZer Peel', category: 'Peeling', price: 125.00, stockStatus: 'IN_STOCK', description: 'Peeling effet laser resurfacing.' },
  // --- MASQUES ---
  { id: 'glass-mask', sku: 'KRX-GM', name: 'Glass Mask (Édition Limitée)', category: 'Masques', price: 65.00, stockStatus: 'OUT_OF_STOCK', description: 'Masque effet peau de verre.' },
  { id: 'exo', sku: 'KRX-EXO', name: 'Exosome Mask', category: 'Masques', price: 85.00, stockStatus: 'IN_STOCK', description: 'Masque régénérant aux exosomes.' },
  { id: 'homecare-sheet-mask-pack-acide-tranexamique-arbutin', sku: 'KRX-HSM-TA', name: 'Home Care Sheet Mask (Acide Tranéxamique + Arbutin)', category: 'Masques', price: 35.00, stockStatus: 'OUT_OF_STOCK', description: 'Pack masques éclaircissants.' },
  { id: 'homecare-sheet-mask-pack-retinol', sku: 'KRX-HSM-RET', name: 'Home Care Sheet Mask Pack (Retinol)', category: 'Masques', price: 38.00, stockStatus: 'IN_STOCK', description: 'Pack masques anti-âge rétinol.' },
  { id: 'homecate-sheet-mask-pack-acide-glycolique', sku: 'KRX-HSM-GLY', name: 'Home Care Sheet Mask Pack (Acide Glycolique)', category: 'Masques', price: 35.00, stockStatus: 'IN_STOCK', description: 'Pack masques exfoliants doux.' },
  { id: 'jelly-mask-lifting-collagen', sku: 'KRX-JM-LC', name: 'Jelly Mask Lifting Collagen', category: 'Masques', price: 55.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel collagène liftant.' },
  { id: 'jelly-mask-hydrating-hyaluron', sku: 'KRX-JM-HH', name: 'Jelly Mask Hydrating Hyaluron', category: 'Masques', price: 55.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel hydratation intense.' },
  { id: 'jelly-mask-glowing-gold', sku: 'KRX-JM-GG', name: 'Jelly Mask Glowing Gold', category: 'Masques', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel or éclat.' },
  { id: 'jelly-mask-super-astaxanthin', sku: 'KRX-JM-SA', name: 'Jelly Mask Whitening Arbutin', category: 'Masques', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel éclaircissant.' },
  { id: 'treatment-booster-biocellullose-mask', sku: 'KRX-TBM', name: 'Treatment & Booster Biocellullose Mask', category: 'Masques', price: 70.00, stockStatus: 'IN_STOCK', description: 'Masque biocellulose booster.' },
  { id: 'pre-extraction-softening-mask', sku: 'KRX-PESM', name: 'Pre Extraction Softening Mask - 220 g', category: 'Masques', price: 48.00, stockStatus: 'LOW_STOCK', description: 'Masque émollient avant extraction.' },
  { id: 'cryo-facial-icy-mask', sku: 'KRX-CFI', name: 'Cryofacial Icy Mask', category: 'Masques', price: 62.00, stockStatus: 'IN_STOCK', description: 'Masque effet cryo apaisant.' },
  { id: 'home-care-sheet-mask-cica', sku: 'KRX-HCSM-C', name: 'Home Care Sheet Mask (CICA)', category: 'Masques', price: 32.00, stockStatus: 'IN_STOCK', description: 'Masque apaisant Cica.' },
  { id: 'mud-to-sheet-mask', sku: 'KRX-MTS', name: 'Mud to Sheet Mask', category: 'Masques', price: 40.00, stockStatus: 'IN_STOCK', description: 'Masque boue purifiant en feuille.' },
  { id: 'home-care-sheet-mask-salicylic', sku: 'KRX-HCSM-S', name: 'Home Care Sheet Mask (Acide Salicylic)', category: 'Masques', price: 34.00, stockStatus: 'IN_STOCK', description: 'Masque purifiant acide salicylique.' },
  { id: 'v-tox-higher-power-lift-mask', sku: 'KRX-VTX', name: 'V-Tox Higher Power', category: 'Masques', price: 85.00, stockStatus: 'IN_STOCK', description: 'Masque effet lifting V-Shape.' },
  // --- MESOBOOSTER AMPOULE ---
  { id: 'meso-booster-ampoule-boto-rx', sku: 'KRX-MBA-BRX', name: 'Meso Booster Ampoule – Boto-RX', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Ampoule effet botox-like.' },
  { id: 'meso-booster-ampoule-ha', sku: 'KRX-MBA-HA', name: 'MesoBooster HA+', category: 'MesoBooster Ampoule', price: 105.00, stockStatus: 'IN_STOCK', description: 'Acide hyaluronique pur stérile.' },
  { id: 'meso-booster-ampoule-derm-acne-control', sku: 'KRX-MBA-DAC', name: 'Meso Booster Ampoule – Hydro Stemcell', category: 'MesoBooster Ampoule', price: 115.00, stockStatus: 'IN_STOCK', description: 'Cellules souches hydratantes.' },
  { id: 'premiun-ampoule-bio-placenta', sku: 'KRX-PABP', name: 'Premium Ampoule - Bio Placenta', category: 'MesoBooster Ampoule', price: 130.00, stockStatus: 'IN_STOCK', description: 'Facteurs de croissance bio-placenta.' },
  { id: 'ampoules-meso-booster-or-24k', sku: 'KRX-MBA-GOLD', name: 'Meso Booster Ampoule – Gold Peptide', category: 'MesoBooster Ampoule', price: 140.00, stockStatus: 'IN_STOCK', description: 'Peptides et or 24k.' },
  { id: 'premium-ampoule-ha-filling-powder', sku: 'KRX-PAHP', name: 'Premium Ampoule - HA Filling Powder', category: 'MesoBooster Ampoule', price: 125.00, stockStatus: 'IN_STOCK', description: 'Poudre HA comblante.' },
  { id: 'premium-ampoule-hair-meso-solution', sku: 'KRX-PAHM', name: 'Premium Ampoule - Hair Meso Solution', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Meso capillaire.' },
  { id: 'meso-booster-ampoule-salmon-dna-pdrn', sku: 'KRX-MBA-PDRN', name: 'Meso Booster Ampoule – Salmon DNA (PDRN)', category: 'MesoBooster Ampoule', price: 135.00, stockStatus: 'IN_STOCK', description: 'ADN de saumon régénérant.' },
  { id: 'ampoule-thread-filled', sku: 'KRX-ATF', name: 'Thread Fill Ampoule', category: 'MesoBooster Ampoule', price: 120.00, stockStatus: 'IN_STOCK', description: 'Ampoule effet fils tenseurs.' },
  { id: 'ampoule-undereye-solution', sku: 'KRX-AUES', name: 'Premium Ampoule - Undereye Solution', category: 'MesoBooster Ampoule', price: 95.00, stockStatus: 'IN_STOCK', description: 'Spécial contour des yeux.' },
  { id: 'meso-booster-ampoule-white-and-bright', sku: 'KRX-MBA-WB', name: 'Meso Booster Ampoule – White and Bright', category: 'MesoBooster Ampoule', price: 115.00, stockStatus: 'IN_STOCK', description: 'Complexe éclaircissant.' },
  { id: 'meso-booster-ampoule-derm-acne-control-1', sku: 'KRX-MBA-DAC1', name: 'Meso Booster Ampoule – Derm Acne Control', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Contrôle acné et sébum.' },
  // --- SÉRUM ---
  { id: 'gluthatione-solution', sku: 'KRX-GLU', name: 'Gluthatione Solution', category: 'Sérum', price: 75.00, stockStatus: 'LOW_STOCK', description: 'Solution éclat au glutathion.' },
  { id: 'hyal-plus-solution', sku: 'KRX-HPS', name: 'Hyal Plus Solution', category: 'Sérum', price: 72.00, stockStatus: 'LOW_STOCK', description: 'Booster hydratation intense.' },
  { id: 'mela-defense-serum', sku: 'KRX-MDS', name: 'Mela Defense Serum', category: 'Sérum', price: 89.00, stockStatus: 'IN_STOCK', description: 'Sérum anti-taches.' },
  { id: 'clinical-line-youthplex-face-lift-serum', sku: 'KRX-YFLS', name: 'Clinical Line Youthplex Face Lift Serum - 30 ml', category: 'Sérum', price: 110.00, stockStatus: 'OUT_OF_STOCK', description: 'Sérum liftant gamme clinique.' },
  { id: 'hair-boost-solution', sku: 'KRX-HBS', name: 'Hair Boost Solution', category: 'Sérum', price: 80.00, stockStatus: 'LOW_STOCK', description: 'Solution boost capillaire.' },
  { id: 'booster-set-4-solutions', sku: 'KRX-BS4', name: 'Booster Set 4 Solutions', category: 'Sérum', price: 250.00, stockStatus: 'LOW_STOCK', description: 'Kit complet 4 boosters.' },
  { id: 'all-day-glow-vitamin-serum', sku: 'KRX-ADGVS', name: 'All Day Glow Vitamin Serum', category: 'Sérum', price: 68.00, stockStatus: 'OUT_OF_STOCK', description: 'Sérum vitaminé éclat quotidien.' },
  { id: 'the-face-lift-intensive-firming-serum', sku: 'KRX-TFLS', name: 'The Face Lift Intensive Firming Serum', category: 'Sérum', price: 95.00, stockStatus: 'IN_STOCK', description: 'Sérum raffermissant intensif.' },
  { id: 'big-cica-recovery-serum-50ml', sku: 'KRX-BCRS', name: 'Big Cica Recovery Serum', category: 'Sérum', price: 78.00, stockStatus: 'LOW_STOCK', description: 'Grand format sérum Cica.' },
  { id: 'phytoxome-exosome-serum', sku: 'KRX-PES', name: 'PhytoXome', category: 'Sérum', price: 145.00, stockStatus: 'IN_STOCK', description: 'Sérum avancé aux exosomes.' },
  { id: 'sdna-repair-shot', sku: 'KRX-SRS', name: 'sDNA Repair Shot', category: 'Sérum', price: 85.00, stockStatus: 'LOW_STOCK', description: 'Shot réparateur ADN.' },
  // --- CRÈME ---
  { id: 'mela-defense-cream', sku: 'KRX-MDC', name: 'Mela Defense Cream - 50 g', category: 'Crème', price: 65.00, stockStatus: 'IN_STOCK', description: 'Crème correctrice pigmentation.' },
  { id: 'essence-cream-pad', sku: 'KRX-ECP', name: 'Essence Cream Pad', category: 'Crème', price: 45.00, stockStatus: 'IN_STOCK', description: 'Disques imprégnés de crème essence.' },
  { id: 'holiday-creme-neck-lift', sku: 'KRX-HNL', name: 'Holiday Crème Neck Lift (Édition Limitée)', category: 'Crème', price: 70.00, stockStatus: 'IN_STOCK', description: 'Crème cou liftante édition fêtes.' },
  { id: 'clinical-line-youthplex-face-lift-cream', sku: 'KRX-YFLC', name: 'Clinical Line Youthplex Face Lift Cream - 50 g', category: 'Crème', price: 98.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème liftante gamme clinique.' },
  { id: 'repair-cream', sku: 'KRX-RC', name: 'Repair Cream', category: 'Crème', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Crème réparatrice barrière cutanée.' },
  { id: 'neck-lift-intensive-firming-cream', sku: 'KRX-NLFC', name: 'Neck Lift Intensive Firming Cream', category: 'Crème', price: 75.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème raffermissante cou.' },
  { id: 'big-cica-recovery-all-day-cream', sku: 'KRX-BCRAC', name: 'Big Cica Recovery All Day Cream', category: 'Crème', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Crème jour récupération Cica.' },
  { id: 'strengthen-amp-protect-probiotic-cream', sku: 'KRX-SPPC', name: 'Strengthen Protect Probiotic Cream', category: 'Crème', price: 62.00, stockStatus: 'IN_STOCK', description: 'Crème probiotique protectrice.' },
  { id: 'all-day-glow-aqua-cream', sku: 'KRX-ADGAC', name: 'All Day Glow Aqua Cream', category: 'Crème', price: 55.00, stockStatus: 'IN_STOCK', description: 'Gel-crème hydratant éclat.' },
  { id: 'active-31-revitalizing-eye-cream', sku: 'KRX-A31', name: 'Active-31 Revitalizing Eye Cream', category: 'Crème', price: 52.00, stockStatus: 'LOW_STOCK', description: 'Crème yeux revitalisante.' },
  { id: 'cocoa-facial-massage-cream', sku: 'KRX-CFMC', name: 'Cocoa Facial Massage Cream', category: 'Crème', price: 48.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème de massage au cacao.' },
  { id: 'clear-prevent-anti-acne-cream', sku: 'KRX-CPAC', name: 'Clear & Prevent Anti Acne Cream', category: 'Crème', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Crème traitante anti-acné.' },
  // --- TONIQUE ---
  { id: 'clear-prevent-anti-acne-face-toner', sku: 'KRX-CPAT', name: 'Clear & Prevent Anti Acne Face Toner', category: 'Tonique', price: 38.00, stockStatus: 'LOW_STOCK', description: 'Tonique purifiant acné.' },
  { id: 'big-cica-recovery-ultra-healing-toner', sku: 'KRX-BCRT', name: 'Big Cica Recovery Ultra Healing Toner', category: 'Tonique', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Tonique réparateur grand format.' },
  { id: 'strengthen-protect-probiotic-toner', sku: 'KRX-SPPT', name: 'Strengthen & Protect Probiotic Toner', category: 'Tonique', price: 40.00, stockStatus: 'LOW_STOCK', description: 'Tonique équilibrant probiotique.' },
  { id: 'clinical-line-youthplex-toner', sku: 'KRX-YPT', name: 'Clinical Line Youthplex Face Lift Toning Solution', category: 'Tonique', price: 55.00, stockStatus: 'OUT_OF_STOCK', description: 'Lotion tonique liftante.' },
  { id: 'quenching-toner-all-day-glow', sku: 'KRX-QTADG', name: 'Quenching Toner All Day Glow', category: 'Tonique', price: 38.00, stockStatus: 'IN_STOCK', description: 'Tonique hydratant éclat.' },
  { id: 'biocell-bc3-cica', sku: 'KRX-BC3', name: 'BioCell+ BC3 "Cica" - 300 ml', category: 'Tonique', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Solution tonique apaisante Cica.' },
  { id: 'biocell-ha-collagen', sku: 'KRX-BC2', name: 'BioCell+ BC2 "HA & Collagen" - 300 ml', category: 'Tonique', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Solution tonique hydratante collagène.' },
  // --- DÉMAQUILLANT - NETTOYANT ---
  { id: 'oxy-glow-bubble-cleanser-spiulina-tiny-pumpple', sku: 'KRX-OGBC', name: 'Oxy Glow Bubble Cleanser "Pumpkin + Blue Tansy + Spirulina"', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant moussant oxygénant.' },
  { id: 'clinical-line-youthplex-cleanser', sku: 'KRX-YPC', name: 'Clinical Line Youthplex Face Lift Cleansing Fluid', category: 'Démaquillant - Nettoyant', price: 48.00, stockStatus: 'OUT_OF_STOCK', description: 'Fluide nettoyant liftant.' },
  { id: 'gel-cleanser-all-day-glow', sku: 'KRX-GCADG', name: 'Gel Cleanser All Day Glow', category: 'Démaquillant - Nettoyant', price: 32.00, stockStatus: 'IN_STOCK', description: 'Gel nettoyant éclat.' },
  { id: 'lait-demaquillant', sku: 'KRX-LDNE', name: 'Lait Démaquillant Nettoyant Enzymatique - 1000 ml', category: 'Démaquillant - Nettoyant', price: 85.00, stockStatus: 'OUT_OF_STOCK', description: 'Lait nettoyant format cabine.' },
  { id: 'lait-demaquillant-nettoyant-enzymatique-antibacterien-1000-ml', sku: 'KRX-LDNEA', name: 'Lait Démaquillant Nettoyant Enzymatique & Antibactérien - 1000 ml', category: 'Démaquillant - Nettoyant', price: 90.00, stockStatus: 'OUT_OF_STOCK', description: 'Lait antibactérien cabine.' },
  { id: 'cica-recovery-2-in-1-mask-cleanser-1', sku: 'KRX-CR21', name: 'Cica Recovery 2 in 1 Mask Cleanser', category: 'Démaquillant - Nettoyant', price: 42.00, stockStatus: 'OUT_OF_STOCK', description: 'Nettoyant et masque apaisant.' },
  { id: 'oxy-glow-bubble-wash-spirulina', sku: 'KRX-OGBS', name: 'Oxy Glow Bubble Cleanser Spirulina - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant spiruline.' },
  { id: 'oxy-glow-bubble-wash-blue-tansy', sku: 'KRX-OGBB', name: 'Oxy Glow Bubble Cleanser Blue Tansy - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant tanaisie bleue.' },
  { id: 'oxy-glow-bubble-wash-pumpkin', sku: 'KRX-OGBP', name: 'Oxy Glow Bubble Cleanser Pumpkin - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant citrouille.' },
  { id: 'clear-prevent-anti-acne-face-wash', sku: 'KRX-CPAW', name: 'Clear & Prevent Anti Acne Face Wash', category: 'Démaquillant - Nettoyant', price: 30.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant visage anti-acné.' },
  { id: 'strengthen-protect-probiotic-face-wash', sku: 'KRX-SPPW', name: 'Strengthen & Protect Probiotic Face Wash', category: 'Démaquillant - Nettoyant', price: 34.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant visage probiotique.' },
  { id: 'lait-nettoyant-enzymatique-antibacterien-250-ml', sku: 'KRX-LNEA-250', name: 'Lait Démaquillant Nettoyant Enzymatique - 250 ml', category: 'Démaquillant - Nettoyant', price: 38.00, stockStatus: 'IN_STOCK', description: 'Lait nettoyant revente.' },
  { id: 'lait-nettoyant-enzymatique-antibacterien-1000-ml-2', sku: 'KRX-LNEA-250-AB', name: 'Lait Démaquillant Nettoyant Enzymatique & Antibactérien - 250 ml', category: 'Démaquillant - Nettoyant', price: 40.00, stockStatus: 'IN_STOCK', description: 'Lait antibactérien revente.' },
  { id: 'huile-nettoyante-demaquillante', sku: 'KRX-HND', name: 'Pre Cleansing Oil', category: 'Démaquillant - Nettoyant', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Huile démaquillante.' },
  // --- TRAITEMENT SPÉCIALISÉ ---
  { id: 'carboxy-therapy-co2-500ml', sku: 'KRX-CT500', name: 'Carboxy Therapy CO2 - 500 ml', category: 'Traitement Spécialisé', price: 160.00, stockStatus: 'LOW_STOCK', description: 'Gel carboxythérapie format pro.' },
  { id: 'carboxy-therapy-co2-1000ml', sku: 'KRX-CT1000', name: 'Carboxy Therapy CO2 - 1000ml', category: 'Traitement Spécialisé', price: 290.00, stockStatus: 'OUT_OF_STOCK', description: 'Gel carboxythérapie format maxi.' },
  { id: 'inflacure-healing-active', sku: 'KRX-IHA', name: 'Inflacure Healing Active', category: 'Traitement Spécialisé', price: 85.00, stockStatus: 'IN_STOCK', description: 'Traitement actif anti-inflammatoire.' },
  { id: 'pd-13-therapy', sku: 'KRX-PD13', name: 'PD-13 Therapy', category: 'Traitement Spécialisé', price: 140.00, stockStatus: 'LOW_STOCK', description: 'Thérapie photodynamique.' },
  { id: 'carboxy-therapy-co-mini-150-ml', sku: 'KRX-CT150', name: 'Carboxy Therapy CO₂ Mini – 150 ml', category: 'Traitement Spécialisé', price: 65.00, stockStatus: 'LOW_STOCK', description: 'Kit essai carboxythérapie.' },
  { id: 'ze-tox', sku: 'KRX-ZTX', name: 'ZE-TOX', category: 'Traitement Spécialisé', price: 120.00, stockStatus: 'IN_STOCK', description: 'Traitement détoxifiant avancé.' },
  { id: 'vitaamedi', sku: 'KRX-VTM', name: 'VITAMEDI Solution', category: 'Traitement Spécialisé', price: 95.00, stockStatus: 'IN_STOCK', description: 'Solution vitaminée médi-esthétique.' },
  // --- SOLUTION HYDRAFACIAL ---
  { id: 'solution-hydrafacial-3-x', sku: 'KRX-SH3', name: 'Solutions BioCell+ "BC1/BC2/BC3" - Pack 3 x 300 ml', category: 'Solution HydraFacial', price: 150.00, stockStatus: 'LOW_STOCK', description: 'Pack complet solutions hydrodermabrasion.' },
  { id: 'hydraskin', sku: 'KRX-HDS', name: 'HydraSkin', category: 'Solution HydraFacial', price: 55.00, stockStatus: 'OUT_OF_STOCK', description: 'Solution hydratante pour machine.' },
  // --- GAMME HOMECARE ---
  { id: 'holiday-pack-acne-edition-limitee', sku: 'KRX-HP-ACNE', name: 'Holiday Set Acné Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes anti-acné.' },
  { id: 'holiday-pack-glow-edition-limitee', sku: 'KRX-HP-GLOW', name: 'Holiday Set Glow Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes éclat.' },
  { id: 'holiday-pack-probiotic-edition-limitee', sku: 'KRX-HP-PROBIO', name: 'Holiday Set Probiotic Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes probiotiques.' },
  { id: 'gamme-complete-strenghten-protect-probiotic', sku: 'KRX-GC-SPP', name: 'Gamme Complète Strenghten & Protect Probiotic', category: 'Gamme HomeCare', price: 180.00, stockStatus: 'LOW_STOCK', description: 'Routine complète probiotique.' },
  { id: 'gamme-complete-clear-prevent-anti-acne', sku: 'KRX-GC-CPA', name: 'Gamme Complète Clear & Prevent Anti Acné', category: 'Gamme HomeCare', price: 175.00, stockStatus: 'LOW_STOCK', description: 'Routine complète acné.' },
  { id: 'gamme-complete-all-day-glow', sku: 'KRX-GC-ADG', name: 'Gamme Complète All Day Glow', category: 'Gamme HomeCare', price: 190.00, stockStatus: 'OUT_OF_STOCK', description: 'Routine complète éclat.' },
  { id: 'gamme-complete-clinical-line-youthplex-face-lift', sku: 'KRX-GC-YFL', name: 'Gamme Clinical Line Youthplex Face Lift', category: 'Gamme HomeCare', price: 250.00, stockStatus: 'OUT_OF_STOCK', description: 'Routine complète lifting.' },
  { id: 'clinical-skin-filler-tinted-sunscreen-light-medium', sku: 'KRX-CSF-LM', name: 'Clinical Skin Filler Tinted Sunscreen (Light-Medium)', category: 'Gamme HomeCare', price: 58.00, stockStatus: 'IN_STOCK', description: 'Protection solaire teintée claire.' },
  { id: 'clinical-skin-filler-tinted-sunscreen-medium-dark', sku: 'KRX-CSF-MD', name: 'Clinical Skin Filler Tinted Sunscreen (Medium-Dark)', category: 'Gamme HomeCare', price: 58.00, stockStatus: 'IN_STOCK', description: 'Protection solaire teintée foncée.' },
  { id: 'all-day-glow-sunblocker-spf-50', sku: 'KRX-ADGS', name: 'All Day Glow Sunblocker SPF 50', category: 'Gamme HomeCare', price: 48.00, stockStatus: 'IN_STOCK', description: 'Protection solaire SPF 50 éclat.' },
  { id: 'trial-package-kit-booster', sku: 'KRX-TPKB', name: 'Trial Package Kit Booster', category: 'Gamme HomeCare', price: 45.00, stockStatus: 'IN_STOCK', description: 'Kit découverte boosters.' },
  { id: 'cica-recovery-set', sku: 'KRX-CRS', name: 'Cica Recovery Set', category: 'Gamme HomeCare', price: 95.00, stockStatus: 'LOW_STOCK', description: 'Set récupération Cica.' },
  { id: 'jelly-mist', sku: 'KRX-JM', name: 'Jelly Mist', category: 'Gamme HomeCare', price: 35.00, stockStatus: 'IN_STOCK', description: 'Brume hydratante gélifiée.' },
  { id: 'patch-microneedling-cernes', sku: 'KRX-PMC', name: 'Patch Microneedling Cernes', category: 'Gamme HomeCare', price: 25.00, stockStatus: 'IN_STOCK', description: 'Patchs yeux micro-aiguilles.' },
  { id: 'patch-microneedling-levres', sku: 'KRX-PML', name: 'Patch Microneedling Lèvres', category: 'Gamme HomeCare', price: 25.00, stockStatus: 'IN_STOCK', description: 'Patchs lèvres micro-aiguilles.' },
  // --- EXFOLIANT ---
  { id: 'cacao-facial-powder-wash', sku: 'KRX-CFPW', name: 'Cocoa Facial Powder Wash - 100 g', category: 'Exfoliant', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Poudre nettoyante enzymatique cacao.' },
  { id: 'skin-prep-exfoliant-solution', sku: 'KRX-SPES', name: 'Skin Prep Exfoliant Solution - 150 ml', category: 'Exfoliant', price: 38.00, stockStatus: 'IN_STOCK', description: 'Solution exfoliante préparatoire.' },
  // --- ACCESSOIRE ---
  { id: 'pinceau-krx-silicone', sku: 'KRX-ACC-SIL', name: 'Pinceau Silicone KRX', category: 'Accessoire', price: 15.00, stockStatus: 'OUT_OF_STOCK', description: 'Pinceau application silicone.' },
  { id: 'pinceau-krx-eventail', sku: 'KRX-ACC-FAN', name: 'Pinceau Eventail KRX', category: 'Accessoire', price: 18.00, stockStatus: 'OUT_OF_STOCK', description: 'Pinceau éventail poils doux.' },
  { id: 'bandeau-krx', sku: 'KRX-ACC-HB', name: 'Bandeau KRX', category: 'Accessoire', price: 12.00, stockStatus: 'OUT_OF_STOCK', description: 'Bandeau soin visage.' },
];

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(withPricing);

export const ACADEMY_CONTENT: AcademyResource[] = [
  { id: 'a1', title: 'Green Sea Peel: Protocoles Fondamentaux', type: 'PDF', tierReq: UserTier.STANDARD, thumbnail: 'https://picsum.photos/400/300?grayscale', duration: '14 pages' },
  { id: 'a2', title: 'Carboxy Therapy: Application Professionnelle', type: 'VIDEO', tierReq: UserTier.STANDARD, thumbnail: 'https://picsum.photos/400/301?grayscale', duration: '12 min' },
  { id: 'a3', title: 'Masterclass: Gestion de l\'Hyperpigmentation', type: 'VIDEO', tierReq: UserTier.PREMIUM, thumbnail: 'https://picsum.photos/400/302?grayscale', duration: '45 min' },
  { id: 'a4', title: 'Certification Avancée: Anti-Âge Cellulaire', type: 'CERTIFICATION', tierReq: UserTier.PREMIUM, thumbnail: 'https://picsum.photos/400/303?grayscale', duration: 'Examen' },
];