import { Translations, Language, UserTier, User, Product, AcademyResource } from './types';

export const TRANSLATIONS: Translations = {
  [Language.FR]: {
    login_title: "Espace Partenaire",
    login_subtitle: "Partenaire KRX Aesthetics",
    login_select_level: "Sélectionnez votre niveau d'accès",
    login_std_title: "STANDARD",
    login_std_subtitle: "Accès essentiel",
    login_std_price: "CHF 300/mois",
    login_std_features: "Commandes, Catalogue produits, Formation base",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Elite Ecosystem",
    login_prem_price: "Dès CHF 800/mois",
    login_prem_features: "Accès multi-niveaux, Tarifs dégressifs, Academy Elite, Priorité stock, Insights business",
    login_btn_access: "ACCÉDER",
    login_no_account: "Vous n'avez pas encore de compte ?",
    login_become_partner: "Devenir partenaire",
    login_back: "Retour",
    login_space_std: "Espace Standard",
    login_space_prem: "Espace Premium",
    login_id_label: "UTILISATEUR",
    login_id_label_prem: "IDENTIFIANT PREMIUM",
    login_pwd_label: "MOT DE PASSE",
    login_secure_std: "Connexion sécurisée DermaKor",
    login_secure_prem: "Accès sécurisé Espace Elite",
    login_btn: "Accéder au Portail",
    login_secure: "Connexion sécurisée par DermaKor Swiss",
    nav_dashboard: "Vue d'ensemble",
    nav_order: "Commande Pro",
    nav_academy: "DermaKor Academy",
    nav_logout: "Déconnexion",
    dash_welcome: "Bienvenue, Dr. ",
    dash_tier_status: "Statut Partenaire",
    dash_progress_title: "Objectif Mensuel",
    dash_min_goal: "Objectif minimum",
    dash_monthly_goal: "Objectif Mensuel",
    dash_active_tier_premium: "Membre Premium Actif",
    dash_current_spend: "Volume actuel",
    dash_recent_orders: "Dernières expéditions",
    dash_order_id: "Réf.",
    dash_date: "Date",
    dash_amount: "Montant",
    dash_status: "État",
    dash_view_all: "Voir tout",
    order_title: "Système de Commande",
    order_subtitle: "Sélectionnez vos produits professionnels pour l'institut.",
    order_col_product: "Référence Produit",
    order_col_price: "Prix Pro (CHF)",
    order_col_qty: "Quantité",
    order_col_total: "Total Ligne",
    order_summary: "Récapitulatif de commande",
    order_submit: "Valider la commande",
    academy_title: "Centre de Formation Professionnel",
    academy_subtitle: "Protocoles avancés et documentation technique.",
    academy_locked: "Réservé Premium",
    academy_view: "Consulter",
    common_premium_badge: "Membre Premium",
    common_standard_badge: "Membre Standard",
    pricing_title: "Gestion des Prix",
    pricing_subtitle: "Configuration des remises globales et individuelles",
    global_config: "Configuration Globale",
    apply_global: "Appliquer Remise Globale",
    save_changes: "Enregistrer les modifications",
    base_price: "Prix de Base",
    std_tier: "Tier Standard",
    prem_tier: "Tier Premium",
    final_price: "Prix Final",
    savings: "Économie",
    method: "Méthode",
    percentage: "Pourcentage (%)",
    fixed: "Prix Fixe (CHF)",
    history: "Historique",
    admin_nav_dashboard: "PANEL EJECUTIVO",
    admin_nav_partners: "PARTENAIRES",
    admin_nav_orders: "COMMANDES",
    admin_nav_products: "PRODUCTOS",
    admin_nav_collections: "COLECCIONES",
    admin_nav_inventory: "INVENTARIO",
    admin_nav_pricing: "STRATÉGIE & PRIX",
    admin_nav_reports: "RAPPORTS",
    admin_nav_settings: "CONFIGURATION",
    admin_nav_vision: "Vision Stratégique",
    admin_nav_academy: "DERMAKOR ACADEMY",
    admin_nav_operational: "OPÉRATIONNEL",
    admin_nav_strategy: "STRATÉGIE",
    admin_logout: "Se déconnecter",
    admin_search_placeholder: "RECHERCHE GLOBALE...",
    catalog_title: "Gestion du Catalogue",
    catalog_search_placeholder: "Rechercher un produit...",
    catalog_tab_all: "Tous",
    catalog_tab_active: "Actifs",
    catalog_tab_draft: "Brouillons",
    catalog_tab_archived: "Archivés",
    catalog_metric_sales_rate: "Taux de vente",
    catalog_metric_inventory_days: "Jours d'inventaire",
    catalog_metric_abc_analysis: "Analyse ABC",
    catalog_table_product: "Produit",
    catalog_table_status: "Statut",
    catalog_table_inventory: "Inventaire",
    catalog_table_category: "Catégorie",
    catalog_table_channels: "Canaux",
    catalog_table_sku: "SKU",
    catalog_table_unavailable: "Indisponible",
    catalog_table_committed: "Engagé",
    catalog_table_available: "Disponible",
    catalog_table_on_hand: "En main",
    partners_title: "Gestion des Partenaires",
    prospects_title: "Gestion des Prospects",
    partners_subtitle: "Administrez et validez les accès au portail.",
    prospects_subtitle: "Visualisez les leads entrants du formulaire externe.",
    partners_table_institute: "Partenaire / Institut",
    partners_table_contact: "Contact & Email",
    partners_table_join_date: "Inscription",
    partners_table_actions: "Actions",
    partners_details: "Détails",
    partners_convert: "Convertir",
    common_export: "Exporter",
    common_import: "Importer",
    common_add_product: "Ajouter produit",
    common_days: "jours",
    common_active: "Actif",
    common_archived: "Archivé",
    common_draft: "Brouillon",
    common_in_stock: "en stock",
    common_back: "Retour",
    common_search: "Rechercher",
    common_no_results: "Aucun produit trouvé",
    catalog_table_title: "Titre",
    catalog_table_conditions: "Conditions des produits",
    catalog_drawer_anatomy: "Anatomie Opérationnelle",
    catalog_drawer_rotation: "Rotation Mensuelle",
    catalog_drawer_sold_this_month: "Unités vendues ce mois",
    catalog_drawer_accumulated_profit: "Profit Accumulé",
    catalog_drawer_total_benefit: "Bénéfice brut total généré",
    catalog_drawer_logistics: "Données Logistiques",
    catalog_drawer_physical_stock: "Stock Physique",
    catalog_drawer_units: "Unités",
    catalog_drawer_edit_tech_sheet: "Éditer Fiche Technique",
    partners_status_pending: "En Attente",
    partners_status_approved: "Approuvé",
    partners_status_rejected: "Refusé",
    partners_add_new: "Nouveau Socio",
    admin_nav_prospects: "Prospects",
    partners_search_placeholder: "Rechercher un institut, email...",
    partners_tab_partners: "Partenaires",
    partners_tab_prospects: "PROSPECTS",
    // Academy Admin & Access
    academy_admin_title: "DERMAKOR ACADEMY",
    academy_admin_subtitle: "Gérez le contenu éducatif et les privilèges d'accès.",
    academy_admin_create: "Créer du Contenu",
    academy_admin_search: "Rechercher par titre ou catégorie...",
    academy_admin_empty: "Aucun contenu academy trouvé.",
    academy_admin_loading: "Chargement de la bibliothèque de contenus...",
    academy_resource_video: "Vidéo Protocole",
    academy_resource_pdf: "Guide PDF",
    academy_resource_course: "Cours Complet",
    academy_resource_masterclass: "Masterclass",
    academy_resource_webinar: "Webinar Enregistré",
    academy_resource_download: "Téléchargeable",
    academy_form_title: "Titre du Contenu",
    academy_form_desc: "Description courte",
    academy_form_type: "Type de Ressource",
    academy_form_cat: "Catégorie",
    academy_form_tier: "Niveau Requis",
    academy_form_status: "Statut",
    academy_form_thumb: "URL de la Miniature",
    academy_form_url_pdf: "URL du Document (PDF)",
    academy_form_url_video: "URL de la Vidéo (Vimeo/YouTube)",
    academy_form_duration: "Durée / Pages",
    academy_form_order: "Ordre d'Apparition",
    academy_form_submit: "Publier dans l'Academy",
    academy_form_update: "Mettre à jour le Contenu",
    academy_form_new: "Nouveau Contenu Academy",
    academy_form_tier_std: "Tous (Standard)",
    academy_form_tier_prem: "Seulement Premium+",
    academy_form_tier_spec: "Sélection Manuelle",
    academy_access_title: "🔐 Accès Dermakor Academy",
    academy_access_active: "Module Actif",
    academy_access_locked: "Module Bloqué",
    academy_access_perm: "Accès Permanent",
    academy_access_temp: "Accès Temporaire",
    academy_access_disable: "Désactiver tout le Module",
    academy_access_expire: "Expire le :",
    academy_access_updated: "Accès à l'Academy mis à jour avec succès.",
    academy_admin_save_error: "Erreur lors de l'enregistrement de la ressource.",
    academy_admin_delete_confirm: "Êtes-vous sûr de vouloir supprimer cette ressource académique ?",
    common_no_description: "Aucune description disponible.",
    common_edit: "Modifier",
    common_delete: "Supprimer",
    academy_form_title_placeholder: "Ex: Masterclass Green Sea Peel",
    academy_form_desc_placeholder: "Décrivez brièvement le contenu de ce module...",
    academy_form_cat_placeholder: "Ex: Protocoles, Marketing, Ventes...",
    academy_form_url_general: "URL du Contenu / Lien",
    academy_form_url_pdf_placeholder: "Collez le lien vers votre PDF ici...",
    academy_form_url_video_placeholder: "Lien Vimeo, YouTube ou S3...",
    academy_form_url_general_placeholder: "Lien vers la ressource...",
    academy_form_duration_placeholder: "Ex: 15 min ou 12 pages",
    // Strategic Order Module
    order_fixed_summary: "Résumé de Rentabilité",
    order_retail_val: "Facturation Retail Estimée",
    order_potential_profit: "Bénéfice Potentiel",
    order_avg_margin: "Margen Moyen du Panier",
    order_tier_advance: "Progression vers Niveau Supérieur",
    order_pack_title: "Optimisez votre commande : Packs Stratégiques",
    order_optimize_btn: "Optimiser pour Maximum de Marge",
    order_roi_alert: "Opportunité Stratégique",
    order_filter_margin: "Marge Élevée",
    order_filter_rotation: "Haute Rotation",
    order_filter_elite: "Priorité Elite",
    order_label_best_seller: "Best Seller Suisse",
    order_label_high_rotation: "Alta Rotación",
    order_label_high_margin: "Marge Élevée",
    order_label_strategic: "Produit Stratégique",
    order_label_tendency: "Tendance Actuelle",
    order_label_recommended: "Recommandé Premium",
    order_unit_profit: "Gain / Unité",
    order_rrp_price: "Prix Vente Conseillé (PVC)",
    common_error: "Une erreur est survenue.",
    academy_access_restricted: "Accès Restreint",
    academy_upsell_badge: "Évolution Professionnelle",
    academy_upsell_title: "Débloquez l'Excellence Clinique",
    academy_upsell_desc: "Atteignez le statut **Premium Partner** avec un volume mensuel de 800 CHF pour débloquer des protocoles vidéo avancés, des masterclasses d'experts et des examens de certification officielle DermaKor.",
    academy_upsell_target: "Objectif d'investissement mensuel",
    academy_upsell_btn: "Voir les avantages Premium",
    partners_loading: "Chargement des partenaires...",
    partners_empty: "Aucun partenaire trouvé.",
    partners_approve: "Approuver",
    partners_reject: "Refuser",
    partners_table_prospect: "Prospect / Institut",
    partners_table_source: "Source",
    partners_lead_date: "Date Lead",
    partners_prospect_empty: "Aucun prospect entrant.",
    partners_main_contact: "Contact Principal",
    partners_business_email: "Email Affaire",
    partners_profile_info: "Informations de Profil",
    partners_location: "Localisation",
    partners_joined: "Date d'entrée",
    partners_tier_level: "Niveau Tier",
    partners_new_title: "Nouveau Partenaire",
    partners_new_subtitle: "Créez un accès pour un nouvel institut",
    partners_label_institute: "Nom de l'institut",
    partners_label_contact: "Nom du contact",
    partners_label_location: "Localisation (Ville)",
    partners_label_tier: "Niveau de Partenariat",
    partners_tier_standard_desc: "Accès de base",
    partners_tier_premium_desc: "Remises Max.",
    partners_btn_create: "Créer le Partenaire",
    // Academy 2.0 Strategic
    academy_level_std: "Niveau Standard (Essentiel)",
    academy_level_prem_base: "Niveau Premium Base",
    academy_level_prem_pro: "Niveau Premium Pro",
    academy_level_prem_elite: "Niveau Premium Elite",
    academy_progress_title: "Votre progression dans Dermakor Academy",
    academy_progress_unlock: "Complétez ce module pour débloquer le niveau suivant",
    academy_lock_title_premium: "Contenu exclusif pour partenaires Premium",
    academy_lock_title_elite: "Contenu exclusif Elite",
    academy_lock_btn_upgrade: "Passer à Premium",
    academy_lock_requirement_elite: "Disponible pour socios Elite (4,000+ CHF mensuels sostenus)",
    academy_stat_efficiency: "Los socios que aplican este protocolo aumentan su volumen promedio 27%",
    academy_certificate_badge: "Certificat de Réussite",
    academy_certificate_download: "Télécharger Certificat (PDF)",
    academy_dash_recommended: "Formation recommandée ce mois",
    academy_dash_new: "Nouveau module disponible",
    academy_dash_trend: "Protocole tendance actuelle",
    catalog_table_web_price: "Prix Public (Web)",
  },
  [Language.DE]: {
    login_title: "Partnerbereich",
    login_subtitle: "KRX Aesthetics Partner",
    login_select_level: "Wählen Sie Ihre Zugangsebene",
    login_std_title: "STANDARD",
    login_std_subtitle: "Basiszugang",
    login_std_price: "CHF 300/Monat",
    login_std_features: "Bestellungen, Produktkatalog, Basisschulung",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Vollzugang",
    login_prem_price: "CHF 800/Monat",
    login_prem_features: "Alles Standard, Vorzugspreise, Academy Elite, VIP Support, Business Insights, Priorität Lager",
    login_btn_access: "ZUGANG",
    login_no_account: "Noch kein Konto?",
    login_become_partner: "Partner werden",
    login_back: "Zurück",
    login_space_std: "Standard Bereich",
    login_space_prem: "Premium Bereich",
    login_id_label: "BENUTZER",
    login_id_label_prem: "PREMIUM BENUTZER",
    login_pwd_label: "PASSWORT",
    login_secure_std: "Sichere Verbindung DermaKor",
    login_secure_prem: "Elite-Verbindung",
    login_btn: "Zum Portal",
    login_secure: "Gesicherte Verbindung durch DermaKor Swiss",
    nav_dashboard: "Übersicht",
    nav_order: "Bestellung",
    nav_academy: "DermaKor Akademie",
    nav_logout: "Abmelden",
    dash_welcome: "Willkommen, Dr. ",
    dash_tier_status: "Partnerstatus",
    dash_progress_title: "Monatsziel",
    dash_min_goal: "Mindestziel",
    dash_monthly_goal: "Monatsziel",
    dash_active_tier_premium: "Aktives Premium-Mitglied",
    dash_current_spend: "Aktuelles Volumen",
    dash_recent_orders: "Letzte Lieferungen",
    dash_order_id: "Ref.",
    dash_date: "Datum",
    dash_amount: "Betrag",
    dash_status: "Status",
    dash_view_all: "Alle ansehen",
    order_title: "Bestellsystem",
    order_subtitle: "Wählen Sie Ihre professionellen Produkte für das Institut.",
    order_col_product: "Produktreferenz",
    order_col_price: "Profi-Preis (CHF)",
    order_col_qty: "Menge",
    order_col_total: "Zeilensumme",
    order_summary: "Bestellübersicht",
    order_submit: "Bestellung bestätigen",
    academy_title: "Professionelles Ausbildungszentrum",
    academy_subtitle: "Fortgeschrittene Protokolle und technische Dokumentation.",
    academy_locked: "Premium Exklusiv",
    academy_view: "Ansehen",
    common_premium_badge: "Premium Mitglied",
    common_standard_badge: "Standard Mitglied",
    pricing_title: "Preisverwaltung",
    pricing_subtitle: "Konfiguration globaler und individueller Rabatte",
    global_config: "Globale Konfiguration",
    apply_global: "Globalen Rabatt anwenden",
    save_changes: "Änderungen speichern",
    base_price: "Basispreis",
    std_tier: "Standard Stufe",
    prem_tier: "Premium Stufe",
    final_price: "Endpreis",
    savings: "Ersparnis",
    method: "Methode",
    percentage: "Prozentsatz (%)",
    fixed: "Festpreis (CHF)",
    history: "Verlauf",
    admin_nav_dashboard: "DASHBOARD",
    admin_nav_partners: "PARTNER",
    admin_nav_orders: "BESTELLUNGEN",
    admin_nav_products: "PRODUKTE",
    admin_nav_collections: "KOLLEKTIONEN",
    admin_nav_inventory: "INVENTAR",
    admin_nav_pricing: "STRATEGIE & PREISE",
    admin_nav_reports: "BERICHTE",
    admin_nav_settings: "Paramètres",
    admin_nav_vision: "Strategische Vision",
    admin_nav_academy: "DERMAKOR ACADEMIE",
    admin_nav_operational: "Opérations",
    admin_nav_strategy: "STRATEGIE",
    admin_logout: "Abmelden",
    admin_search_placeholder: "GLOBALE SUCHE...",
    catalog_title: "Katalogverwaltung",
    catalog_search_placeholder: "Produkt suchen...",
    catalog_tab_all: "Alle",
    catalog_tab_active: "Aktiv",
    catalog_tab_draft: "Entwürfe",
    catalog_tab_archived: "Archiviert",
    catalog_metric_sales_rate: "Verkaufsrate",
    catalog_metric_inventory_days: "Inventartage",
    catalog_metric_abc_analysis: "ABC-Analyse",
    catalog_table_product: "Produkt",
    catalog_table_status: "Status",
    catalog_table_inventory: "Inventar",
    catalog_table_category: "Kategorie",
    catalog_table_channels: "Kanäle",
    catalog_table_sku: "SKU",
    catalog_table_unavailable: "Nicht verfügbar",
    catalog_table_committed: "Verpflichtet",
    catalog_table_available: "Verfügbar",
    catalog_table_on_hand: "Vorhanden",
    partners_title: "Partnerverwaltung",
    prospects_title: "Interessentenverwaltung",
    partners_subtitle: "Verwalten und validieren Sie Portalzugänge.",
    prospects_subtitle: "Eingehende Leads aus dem externen Formular anzeigen.",
    partners_tab_partners: "Partner",
    partners_tab_prospects: "Interessenten",
    partners_table_institute: "Partner / Institut",
    partners_table_contact: "Kontakt & E-Mail",
    partners_table_join_date: "Anmeldung",
    partners_table_actions: "Aktionen",
    partners_details: "Details",
    partners_convert: "Konvertieren",
    common_export: "Exportieren",
    common_import: "Importieren",
    common_add_product: "Produkt hinzufügen",
    common_days: "Tage",
    common_active: "Aktiv",
    common_archived: "Archiviert",
    common_draft: "Entwurf",
    common_in_stock: "auf Lager",
    common_back: "Zurück",
    common_search: "Suchen",
    common_no_results: "Keine Produkte gefunden",
    catalog_table_title: "Titel",
    catalog_table_conditions: "Produktbedingungen",
    catalog_drawer_anatomy: "Operative Anatomie",
    catalog_drawer_rotation: "Monatliche Rotation",
    catalog_drawer_sold_this_month: "Diesen Monat verkaufte Einheiten",
    catalog_drawer_accumulated_profit: "Akkumulierter Gewinn",
    catalog_drawer_total_benefit: "Gesamter Bruttogewinn",
    catalog_drawer_logistics: "Logistikdaten",
    catalog_drawer_physical_stock: "Physischer Bestand",
    catalog_drawer_units: "Einheiten",
    catalog_drawer_edit_tech_sheet: "Technisches Datenblatt bearbeiten",
    partners_status_pending: "Ausstehend",
    partners_status_approved: "Genehmigt",
    partners_status_rejected: "Abgelehnt",
    partners_add_new: "Neuer Partner",
    admin_nav_prospects: "Interessenten",
    partners_search_placeholder: "Suche nach Institut, E-Mail...",
    // Academy Admin & Access
    academy_admin_title: "DERMAKOR AKADEMIE",
    academy_admin_subtitle: "Verwalten Sie Bildungsinhalte und Zugriffsberechtigungen.",
    academy_admin_create: "Inhalt erstellen",
    academy_admin_search: "Nach Titel oder Kategorie suchen...",
    academy_admin_empty: "Keine Akademie-Inhalte gefunden.",
    academy_admin_loading: "Inhaltsbibliothek wird geladen...",
    academy_resource_video: "Protokoll-Video",
    academy_resource_pdf: "PDF-Leitfaden",
    academy_resource_course: "Vollständiger Kurs",
    academy_resource_masterclass: "Masterclass",
    academy_resource_webinar: "Aufgezeichnetes Webinar",
    academy_resource_download: "Herunterladbar",
    academy_form_title: "Inhaltstitel",
    academy_form_desc: "Kurzbeschreibung",
    academy_form_type: "Ressourcentyp",
    academy_form_cat: "Kategorie",
    academy_form_tier: "Erforderliches Level",
    academy_form_status: "Status",
    academy_form_thumb: "Vorschaubild-URL",
    academy_form_url_pdf: "Dokumenten-URL (PDF)",
    academy_form_url_video: "Video-URL (Vimeo/YouTube)",
    academy_form_duration: "Dauer / Seiten",
    academy_form_order: "Reihenfolge",
    academy_form_submit: "In der Akademie veröffentlichen",
    academy_form_update: "Inhalt aktualisieren",
    academy_form_new: "Neuer Akademie-Inhalt",
    academy_form_tier_std: "Alle (Standard)",
    academy_form_tier_prem: "Nur Premium+",
    academy_form_tier_spec: "Manuelle Auswahl",
    academy_access_title: "🔐 Dermakor Akademie Zugang",
    academy_access_active: "Modul aktiv",
    academy_access_locked: "Modul gesperrt",
    academy_access_perm: "Dauerhafter Zugang",
    academy_access_temp: "Temporärer Zugang",
    academy_access_disable: "Gesamtes Modul deaktivieren",
    academy_access_expire: "Läuft ab am:",
    academy_access_updated: "Akademie-Zugang erfolgreich aktualisiert.",
    academy_admin_save_error: "Fehler beim Speichern der Ressource.",
    academy_admin_delete_confirm: "Sind Sie sicher, dass Sie diese Akademie-Ressource löschen möchten?",
    common_no_description: "Keine Beschreibung verfügbar.",
    common_edit: "Bearbeiten",
    common_delete: "Löschen",
    academy_form_title_placeholder: "z.B. Masterclass Green Sea Peel",
    academy_form_desc_placeholder: "Beschreiben Sie kurz, worum es in diesem Modul geht...",
    academy_form_cat_placeholder: "z.B. Protokolle, Marketing, Vertrieb...",
    academy_form_url_general: "Inhalts-URL / Link",
    academy_form_url_pdf_placeholder: "Fügen Sie hier den Link zu Ihrem PDF ein...",
    academy_form_url_video_placeholder: "Link zu Vimeo, YouTube oder S3...",
    academy_form_url_general_placeholder: "Link zur Ressource...",
    academy_form_duration_placeholder: "z.B. 15 Min. oder 12 Seiten",
    // Strategic Order Module
    order_fixed_summary: "Rentabilitätsübersicht",
    order_retail_val: "Geschätzter Einzelhandelsumsatz",
    order_potential_profit: "Potenzieller Gewinn",
    order_avg_margin: "Durchschnittliche Marge",
    order_tier_advance: "Fortschritt zum nächsten Level",
    order_pack_title: "Optimieren Sie Ihre Bestellung: Strategische Pakete",
    order_optimize_btn: "Für maximale Marge optimieren",
    order_roi_alert: "Strategische Gelegenheit",
    order_filter_margin: "Hohe Marge",
    order_filter_rotation: "Hoher Umschlag",
    order_filter_elite: "Elite-Priorität",
    order_label_best_seller: "Bestseller Schweiz",
    order_label_high_rotation: "Hoher Umschlag",
    order_label_high_margin: "Hohe Marge",
    order_label_strategic: "Strategisches Produkt",
    order_label_tendency: "Aktueller Trend",
    order_label_recommended: "Premium Empfohlen",
    order_unit_profit: "Gewinn / Einheit",
    order_rrp_price: "Unverbindliche Preisempfehlung (UVP)",
    common_error: "Ein Fehler ist aufgetreten.",
    academy_access_restricted: "Eingeschränkter Zugriff",
    academy_upsell_badge: "Berufliche Weiterentwicklung",
    academy_upsell_title: "Schalten Sie Klinische Exzellenz frei",
    academy_upsell_desc: "Erreichen Sie den Status **Premium Partner** mit einem monatlichen Volumen von 800 CHF, um fortgeschrittene Videoprotokolle, Experten-Masterclasses und offizielle DermaKor-Zertifizierungsprüfungen freizuschalten.",
    academy_upsell_target: "Monatliches Investitionsziel",
    academy_upsell_btn: "Premium-Vorteile ansehen",
    partners_loading: "Partner werden geladen...",
    partners_empty: "Keine Partner gefunden.",
    partners_approve: "Genehmigen",
    partners_reject: "Ablehnen",
    partners_table_prospect: "Interessent / Institut",
    partners_table_source: "Quelle",
    partners_lead_date: "Lead-Datum",
    partners_prospect_empty: "Keine eingehenden Interessenten.",
    partners_main_contact: "Hauptkontakt",
    partners_business_email: "Geschäftliche E-Mail",
    partners_profile_info: "Profilinformationen",
    partners_location: "Standort",
    partners_joined: "Eintrittsdatum",
    partners_tier_level: "Tier-Ebene",
    partners_new_title: "Neuer Partner",
    partners_new_subtitle: "Zugang für ein neues Institut erstellen",
    partners_label_institute: "Name des Instituts",
    partners_label_contact: "Name des Kontakts",
    partners_label_location: "Standort (Stadt)",
    partners_label_tier: "Partnerschaftsebene",
    partners_tier_standard_desc: "Basiszugang",
    partners_tier_premium_desc: "Max. Rabatte",
    partners_btn_create: "Partner erstellen",
    // Academy 2.0 Strategic
    academy_level_std: "Standard Level (Basis)",
    academy_level_prem_base: "Premium Base Level",
    academy_level_prem_pro: "Premium Pro Level",
    academy_level_prem_elite: "Premium Elite Level",
    academy_progress_title: "Ihr Fortschritt in der Dermakor Academy",
    academy_progress_unlock: "Schließen Sie dieses Modul ab, um das nächste Level freizuschalten",
    academy_lock_title_premium: "Exklusiver Inhalt für Premium-Partner",
    academy_lock_title_elite: "Exklusiver Elite-Inhalt",
    academy_lock_btn_upgrade: "Auf Premium upgraden",
    academy_lock_requirement_elite: "Verfügbar für Elite-Partner (4,000+ CHF nachhaltiger Monatsumsatz)",
    academy_stat_efficiency: "Partner, die dieses Protokoll anwenden, steigern ihr Volumen im Durchschnitt um 27%",
    academy_certificate_badge: "Erfolgszertifikat",
    academy_certificate_download: "Zertifikat herunterladen (PDF)",
    academy_dash_recommended: "Empfohlene Schulung diesen Monat",
    academy_dash_new: "Neues Modul verfügbar",
    academy_dash_trend: "Aktuelles Trend-Protokoll",
    catalog_table_web_price: "Öffentlicher Preis (Web)",
  },
  [Language.IT]: {
    login_title: "Area Partner",
    login_subtitle: "Partner KRX Aesthetics",
    login_select_level: "Seleziona il tuo livello di accesso",
    login_std_title: "STANDARD",
    login_std_subtitle: "Accesso essenziale",
    login_std_price: "CHF 300/mese",
    login_std_features: "Ordini, Catalogo prodotti, Formazione base",
    login_prem_title: "PREMIUM",
    login_prem_subtitle: "Accesso integrale",
    login_prem_price: "CHF 800/mese",
    login_prem_features: "Tutto Standard, Prezzi preferenziali, Academy Elite, Supporto VIP, Approfondimenti business, Priorità stock",
    login_btn_access: "ACCEDI",
    login_no_account: "Non hai ancora un account?",
    login_become_partner: "Diventa partner",
    login_back: "Indietro",
    login_space_std: "Area Standard",
    login_space_prem: "Area Premium",
    login_id_label: "UTENTE",
    login_id_label_prem: "UTENTE PREMIUM",
    login_pwd_label: "PASSWORD",
    login_secure_std: "Connessione sicura DermaKor",
    login_secure_prem: "Connessione Elite",
    login_btn: "Accedi al Portale",
    login_secure: "Connessione sicura da DermaKor Swiss",
    nav_dashboard: "Panoramica",
    nav_order: "Ordini Pro",
    nav_academy: "Accademia DermaKor",
    nav_logout: "Esci",
    dash_welcome: "Benvenuto, Dr. ",
    dash_tier_status: "Stato Partner",
    dash_progress_title: "Obiettivo Mensile",
    dash_min_goal: "Obiettivo Minimo",
    dash_monthly_goal: "Obiettivo Mensile",
    dash_active_tier_premium: "Membro Premium Attivo",
    dash_current_spend: "Volume Attuale",
    dash_recent_orders: "Ultime Spedizioni",
    dash_order_id: "Rif.",
    dash_date: "Data",
    dash_amount: "Importo",
    dash_status: "Stato",
    dash_view_all: "Vedi tutto",
    order_title: "Sistema di Ordinazione",
    order_subtitle: "Seleziona i prodotti professionali per l'istituto.",
    order_col_product: "Riferimento Prodotto",
    order_col_price: "Prezzo Pro (CHF)",
    order_col_qty: "Quantità",
    order_col_total: "Totale Riga",
    order_summary: "Riepilogo Ordine",
    order_submit: "Conferma Ordine",
    academy_title: "Centro Formazione Professionale",
    academy_subtitle: "Protocolli avanzati e documentazione tecnica.",
    academy_locked: "Riservato Premium",
    academy_view: "Visualizza",
    common_premium_badge: "Membro Premium",
    common_standard_badge: "Membro Standard",
    pricing_title: "Gestione Prezzi",
    pricing_subtitle: "Configurazione sconti globali e individuali",
    global_config: "Configurazione Globale",
    apply_global: "Applica Sconto Globale",
    save_changes: "Salva modifiche",
    base_price: "Prezzo Base",
    std_tier: "Livello Standard",
    prem_tier: "Livello Premium",
    final_price: "Prezzo Finale",
    savings: "Risparmio",
    method: "Metodo",
    percentage: "Percentuale (%)",
    fixed: "Prezzo Fisso (CHF)",
    history: "Cronologia",
    admin_nav_dashboard: "DASHBOARD",
    admin_nav_partners: "PARTNER",
    admin_nav_orders: "ORDINI",
    admin_nav_products: "PRODOTTI",
    admin_nav_collections: "COLLEZIONI",
    admin_nav_inventory: "INVENTARIO",
    admin_nav_pricing: "STRATEGIA & PREZZI",
    admin_nav_reports: "RAPPORTI",
    admin_nav_settings: "CONFIGURAZIONE",
    admin_nav_vision: "Visione Strategica",
    admin_nav_academy: "DERMAKOR ACADEMY",
    admin_nav_operational: "OPERATIVO",
    admin_nav_strategy: "STRATEGIA",
    admin_logout: "Disconnettersi",
    admin_search_placeholder: "RICERCA GLOBALE...",
    catalog_title: "Gestione Catalogo",
    catalog_search_placeholder: "Cerca prodotto...",
    catalog_tab_all: "Tutti",
    catalog_tab_active: "Attivi",
    catalog_tab_draft: "Bozze",
    catalog_tab_archived: "Archiviati",
    catalog_metric_sales_rate: "Tasso di vendita",
    catalog_metric_inventory_days: "Giorni di inventario",
    catalog_metric_abc_analysis: "Analisi ABC",
    catalog_table_product: "Prodotto",
    catalog_table_status: "Stato",
    catalog_table_inventory: "Inventario",
    catalog_table_category: "Categoria",
    catalog_table_channels: "Canali",
    catalog_table_sku: "SKU",
    catalog_table_unavailable: "Non disponibile",
    catalog_table_committed: "Impegnato",
    catalog_table_available: "Disponibile",
    catalog_table_on_hand: "A disposizione",
    partners_title: "Gestione Partner",
    prospects_title: "Gestione Prospect",
    partners_subtitle: "Amministra e convalida gli accessi al portale.",
    prospects_subtitle: "Visualizza i lead in entrata dal modulo esterno.",
    partners_tab_partners: "Partner",
    partners_tab_prospects: "Prospect",
    partners_table_institute: "Socio / Istituto",
    partners_table_contact: "Contatto & Email",
    partners_table_join_date: "Iscrizione",
    partners_table_actions: "Azioni",
    partners_details: "Dettagli",
    partners_convert: "Convertire",
    common_export: "Esportare",
    common_import: "Importare",
    common_add_product: "Aggiungi prodotto",
    common_days: "giorni",
    common_active: "Attivo",
    common_archived: "Archiviato",
    common_draft: "Bozza",
    common_in_stock: "in stock",
    common_back: "Indietro",
    common_search: "Cerca",
    common_no_results: "Nessun prodotto trovato",
    catalog_table_title: "Titolo",
    catalog_table_conditions: "Condizioni del prodotto",
    catalog_drawer_anatomy: "Anatomia Operativa",
    catalog_drawer_rotation: "Rotazione Mensile",
    catalog_drawer_sold_this_month: "Unità vendute questo mese",
    catalog_drawer_accumulated_profit: "Profitto Accumulato",
    catalog_drawer_total_benefit: "Utile lordo totale generato",
    catalog_drawer_logistics: "Dati Logistici",
    catalog_drawer_physical_stock: "Stock Fisico",
    catalog_drawer_units: "Unità",
    catalog_drawer_edit_tech_sheet: "Modifica Scheda Tecnica",
    partners_status_pending: "In Attesa",
    partners_status_approved: "Approvato",
    partners_status_rejected: "Rifiutato",
    partners_add_new: "Nuovo Socio",
    admin_nav_prospects: "Prospect",
    partners_search_placeholder: "Cerca per istituto, email...",
    // Academy Admin & Access
    academy_admin_title: "DERMAKOR ACADEMY",
    academy_admin_subtitle: "Gestisci i contenuti educativi e i privilegi di accesso.",
    academy_admin_create: "Crea Contenuto",
    academy_admin_search: "Cerca per titolo o categoria...",
    academy_admin_empty: "Nessun contenuto academy trovato.",
    academy_admin_loading: "Caricamento della libreria dei contenuti...",
    academy_resource_video: "Video Protocollo",
    academy_resource_pdf: "Guida PDF",
    academy_resource_course: "Corso Completo",
    academy_resource_masterclass: "Masterclass",
    academy_resource_webinar: "Webinar Registrato",
    academy_resource_download: "Scaricabile",
    academy_form_title: "Titolo del Contenuto",
    academy_form_desc: "Breve descrizione",
    academy_form_type: "Tipo di Risorsa",
    academy_form_cat: "Categoria",
    academy_form_tier: "Livello Richiesto",
    academy_form_status: "Stato",
    academy_form_thumb: "URL Miniatura",
    academy_form_url_pdf: "URL del Documento (PDF)",
    academy_form_url_video: "URL del Video (Vimeo/YouTube)",
    academy_form_duration: "Durata / Pagine",
    academy_form_order: "Ordine di Apparizione",
    academy_form_submit: "Pubblica in Academy",
    academy_form_update: "Aggiorna Contenuto",
    academy_form_new: "Nuovo Contenuto Academy",
    academy_form_tier_std: "Tutti (Standard)",
    academy_form_tier_prem: "Solo Premium+",
    academy_form_tier_spec: "Selezione Manuale",
    academy_access_title: "🔐 Accesso Dermakor Academy",
    academy_access_active: "Modulo Attivo",
    academy_access_locked: "Modulo Bloccato",
    academy_access_perm: "Accesso Permanente",
    academy_access_temp: "Accesso Temporaneo",
    academy_access_disable: "Disattiva tutto il Modulo",
    academy_access_expire: "Scade il:",
    academy_access_updated: "Accesso alla Academy aggiornato con successo.",
    academy_admin_save_error: "Errore durante il salvataggio della risorsa.",
    academy_admin_delete_confirm: "Sei sicuro di voler eliminare questa risorsa accademica?",
    common_no_description: "Nessuna descrizione disponibile.",
    common_edit: "Modifica",
    common_delete: "Elimina",
    academy_form_title_placeholder: "Es: Masterclass Green Sea Peel",
    academy_form_desc_placeholder: "Descrivi brevemente di cosa tratta questo modulo...",
    academy_form_cat_placeholder: "Es: Protocolli, Marketing, Vendite...",
    academy_form_url_general: "URL del Contenuto / Link",
    academy_form_url_pdf_placeholder: "Incolla qui il link al tuo PDF...",
    academy_form_url_video_placeholder: "Link Vimeo, YouTube o S3...",
    academy_form_url_general_placeholder: "Link alla risorsa...",
    academy_form_duration_placeholder: "Es: 15 min o 12 pagine",
    // Strategic Order Module
    order_fixed_summary: "Sommario di Redditività",
    order_retail_val: "Fatturazione Retail Stimata",
    order_potential_profit: "Profitto Potenziale",
    order_avg_margin: "Margine Medio",
    order_tier_advance: "Progressione Livello Superiore",
    order_pack_title: "Ottimizza il tuo ordine: Pack Strategici",
    order_optimize_btn: "Ottimizza per Massimo Margine",
    order_roi_alert: "Opportunità Strategica",
    order_filter_margin: "Margine Elevato",
    order_filter_rotation: "Alta Rotazione",
    order_filter_elite: "Priorità Elite",
    order_label_best_seller: "Best Seller Svizzera",
    order_label_high_rotation: "Alta Rotazione",
    order_label_high_margin: "Margine Elevato",
    order_label_strategic: "Prodotto Strategico",
    order_label_tendency: "Tendenza Attuale",
    order_label_recommended: "Raccomandato Premium",
    order_unit_profit: "Guadagno / Unità",
    order_rrp_price: "Prezzo di Vendita Conseigliato (PVC)",
    common_error: "Si è verificato un errore.",
    academy_access_restricted: "Accesso Limitato",
    academy_upsell_badge: "Evoluzione Professionale",
    academy_upsell_title: "Sblocca l'Eccellenza Clinica",
    academy_upsell_desc: "Raggiungi lo status di **Partner Premium** con un volume mensile di 800 CHF per sbloccare protocolli video avanzati, masterclass di esperti ed esami di certificazione ufficiale DermaKor.",
    academy_upsell_target: "Obiettivo di investimento mensile",
    academy_upsell_btn: "Vedi i vantaggi Premium",
    partners_loading: "Caricamento partner...",
    partners_empty: "Nessun partner trovato.",
    partners_approve: "Approvare",
    partners_reject: "Rifiutare",
    partners_table_prospect: "Prospect / Istituto",
    partners_table_source: "Fonte",
    partners_lead_date: "Data Lead",
    partners_prospect_empty: "Nessun prospect in entrata.",
    partners_main_contact: "Contatto Principale",
    partners_business_email: "Email Aziendale",
    partners_profile_info: "Informazioni sul Profilo",
    partners_location: "Localizzazione",
    partners_joined: "Data di ingresso",
    partners_tier_level: "Livello Tier",
    partners_new_title: "Nuovo Partner",
    partners_new_subtitle: "Crea un accesso per un nuovo istituto",
    partners_label_institute: "Nome dell'istituto",
    partners_label_contact: "Nome del contatto",
    partners_label_location: "Localizzazione (Città)",
    partners_label_tier: "Livello di Partnership",
    partners_tier_standard_desc: "Accesso base",
    partners_tier_premium_desc: "Sconti Max.",
    partners_btn_create: "Crea Partner",
    // Academy 2.0 Strategic
    academy_level_std: "Livello Standard (Essenziale)",
    academy_level_prem_base: "Livello Premium Base",
    academy_level_prem_pro: "Livello Premium Pro",
    academy_level_prem_elite: "Livello Premium Elite",
    academy_progress_title: "Il tuo progresso nella Dermakor Academy",
    academy_progress_unlock: "Completa questo modulo per sbloccare il livello successivo",
    academy_lock_title_premium: "Contenuto esclusivo per partner Premium",
    academy_lock_title_elite: "Contenuto esclusivo Elite",
    academy_lock_btn_upgrade: "Passa a Premium",
    academy_lock_requirement_elite: "Disponibile per partner Elite (4,000+ CHF mensili sostenuti)",
    academy_stat_efficiency: "I partner che applicano questo protocollo aumentano il loro volume medio del 27%",
    academy_certificate_badge: "Certificato di Successo",
    academy_certificate_download: "Scarica Certificato (PDF)",
    academy_dash_recommended: "Formazione consigliata questo mese",
    academy_dash_new: "Nuovo modulo disponibile",
    academy_dash_trend: "Protocollo tendenza attuale",
    catalog_table_web_price: "Prezzo Pubblico (Web)",
  },
};

export const MOCK_USER: User = {
  id: 'u123',
  name: 'Sophie Dubois',
  instituteName: 'Institut Esthétique Léman',
  tier: UserTier.STANDARD,
  currentSpend: 2150,
  monthlyGoal: 3000,
  consecutiveMonths: 3
};

export const PRODUCT_CATEGORIES = [
  "Tous les produits",
  "Gamme HomeCare",
  "Sérum",
  "Crème",
  "Tonique",
  "Démaquillant - Nettoyant",
  "Traitement Spécialisé",
  "Masque Concentré",
  "Meso Booster Ampoule",
  "Exfoliant",
  "Soin Peeling",
  "Gamme Pfect-A",
  "Solution HydraFacial",
  "Accessoire"
];

// Helper to init pricing
const withPricing = (prod: any) => {
  const retailPrice = prod.retailPrice || 0; // Eliminado el multiplicador 1.6
  const unitProfit = retailPrice > 0 ? retailPrice - prod.price : 0;
  const marginAtRetail = retailPrice > 0 ? Math.round((unitProfit / retailPrice) * 100) : 0;

  return {
    ...prod,
    retailPrice,
    unitProfit,
    marginAtRetail,
    pricing: {
      basePrice: prod.price,
      standard: { type: 'PERCENTAGE', value: 0 },
      premium: { type: 'PERCENTAGE', value: 10 } // Default 10% premium discount for mock
    }
  };
};

export const STRATEGIC_PACKS: any[] = [
  {
    id: 'pack-rotation-alta',
    name: 'Pack Rotación Alta',
    price: 1200,
    description: 'Sélection des 10 best-sellers pour un flux de trésorerie immédiat.',
    badge: 'CONSEILLÉ',
    items: [
      { productId: 'green-sea-peel', quantity: 5 },
      { productId: 'biocell-bc1-aha-bha', quantity: 3 },
      { productId: 'cica-recovery-set', quantity: 4 }
    ]
  },
  {
    id: 'pack-clinique-anti-age',
    name: 'Pack Clinique Anti-Age',
    price: 2500,
    description: 'Protocoles avancés pour rajeunissement cellulaire et lifting.',
    badge: 'MARGE HAUTE',
    items: [
      { productId: 'v-tox-higher-power-lift-mask', quantity: 10 },
      { productId: 'exo', quantity: 5 },
      { productId: 'carboxy-therapy-co2-1000ml', quantity: 2 }
    ]
  },
  {
    id: 'pack-elite-20',
    name: 'Pack Elite 20',
    price: 4500,
    description: 'Volume maximal pour accès prioritaire et support marketing VIP.',
    badge: 'ELITE SELECTION',
    items: [
      { productId: 'mela-pro-plus-cold-peel', quantity: 12 },
      { productId: 'carboxy-therapy-co2-1000ml', quantity: 5 },
      { productId: 'solution-hydrafacial-3-x', quantity: 5 }
    ]
  }
];

const RAW_PRODUCTS: Product[] = [
  // --- PEELING ---
  { id: 'biocell-bc1-aha-bha', sku: 'KRX-BC1', name: 'BioCell+ BC1 "AHA & BHA" - 300 ml', category: 'Peeling', price: 95.00, stockStatus: 'LOW_STOCK', description: 'Solution peeling AHA/BHA professionnelle.', strategicLabel: 'HIGH_ROTATION' },
  { id: 'pre-peel-toner', sku: 'KRX-PPT', name: 'Pre Peel Toner', category: 'Peeling', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Préparation essentielle avant peeling.' },
  { id: 'illumin-biphasic-peeling-solution', sku: 'KRX-IBPS', name: 'Illumin Biphasic Peeling Solution', category: 'Peeling', price: 120.00, stockStatus: 'IN_STOCK', description: 'Solution peeling biphasique illuminatrice.', strategicLabel: 'HIGH_MARGIN' },
  { id: 'blue-peel', sku: 'KRX-BLP', name: 'Blue Peel - 50 ml', category: 'Peeling', price: 85.00, stockStatus: 'LOW_STOCK', description: 'Peeling bleu intensif.' },
  { id: 'brightening-peel', sku: 'KRX-BRP', name: 'Brightening Peel', category: 'Peeling', price: 90.00, stockStatus: 'IN_STOCK', description: 'Peeling éclaircissant.' },
  { id: 'pre-peel-cleanser', sku: 'KRX-PPC', name: 'Pre Peel Cleanser', category: 'Peeling', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant préparatoire peeling.' },
  { id: 'post-peel-toner', sku: 'KRX-POT', name: 'Post Peel Toner', category: 'Peeling', price: 45.00, stockStatus: 'IN_STOCK', description: 'Tonique apaisant post-peeling.' },
  { id: 'glow-peel', sku: 'KRX-GLP', name: 'Glow Peel', category: 'Peeling', price: 95.00, stockStatus: 'IN_STOCK', description: 'Peeling éclat immédiat.', strategicLabel: 'BEST_SELLER' },
  { id: 'clear-peel', sku: 'KRX-CLP', name: 'Clear Peel', category: 'Peeling', price: 92.00, stockStatus: 'IN_STOCK', description: 'Peeling purifiant anti-imperfections.' },
  { id: 'green-sea-peel', sku: 'KRX-GSP', name: 'Green Sea Peel', category: 'Peeling', price: 130.00, stockStatus: 'IN_STOCK', description: 'Spicules marins bio-microneedling.', strategicLabel: 'STRATEGIC' },
  { id: 'r3-therapeel', sku: 'KRX-R3T', name: 'R3 Therapeel', category: 'Peeling', price: 110.00, stockStatus: 'IN_STOCK', description: 'Peeling thérapeutique régénérant.' },
  { id: 'mela-pro-plus-cold-peel', sku: 'KRX-MPP', name: 'MelaPro Plus Cold Peel', category: 'Peeling', price: 140.00, stockStatus: 'IN_STOCK', description: 'Peeling froid dépigmentant.' },
  { id: 'lazer-peel', sku: 'KRX-LZP', name: 'LaZer Peel', category: 'Peeling', price: 125.00, stockStatus: 'IN_STOCK', description: 'Peeling effet laser resurfacing.' },
  // --- MASQUES ---
  { id: 'glass-mask', sku: 'KRX-GM', name: 'Glass Mask (Édition Limitée)', category: 'Masques', price: 65.00, stockStatus: 'OUT_OF_STOCK', description: 'Masque effet peau de verre.' },
  { id: 'exo', sku: 'KRX-EXO', name: 'Exosome Mask', category: 'Masques', price: 85.00, stockStatus: 'IN_STOCK', description: 'Masque régénérant aux exosomes.' },
  { id: 'homecare-sheet-mask-pack-acide-tranexamique-arbutin', sku: 'KRX-HSM-TA', name: 'Home Care Sheet Mask (Acide Tranéxamique + Arbutin)', category: 'Masques', price: 35.00, stockStatus: 'OUT_OF_STOCK', description: 'Pack masques éclaircissants.' },
  { id: 'homecare-sheet-mask-pack-retinol', sku: 'KRX-HSM-RET', name: 'Home Care Sheet Mask Pack (Retinol)', category: 'Masques', price: 38.00, stockStatus: 'IN_STOCK', description: 'Pack masques anti-âge rétinol.' },
  { id: 'homecate-sheet-mask-pack-acide-glycolique', sku: 'KRX-HSM-GLY', name: 'Home Care Sheet Mask Pack (Acide Glycolique)', category: 'Masques', price: 35.00, stockStatus: 'IN_STOCK', description: 'Pack masques exfoliants doux.' },
  { id: 'jelly-mask-lifting-collagen', sku: 'KRX-JM-LC', name: 'Jelly Mask Lifting Collagen', category: 'Masques', price: 55.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel collagène liftant.' },
  { id: 'jelly-mask-hydrating-hyaluron', sku: 'KRX-JM-HH', name: 'Jelly Mask Hydrating Hyaluron', category: 'Masques', price: 55.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel hydratation intense.' },
  { id: 'jelly-mask-glowing-gold', sku: 'KRX-JM-GG', name: 'Jelly Mask Glowing Gold', category: 'Masques', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel or éclat.' },
  { id: 'jelly-mask-super-astaxanthin', sku: 'KRX-JM-SA', name: 'Jelly Mask Whitening Arbutin', category: 'Masques', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Masque hydrogel éclaircissant.' },
  { id: 'treatment-booster-biocellullose-mask', sku: 'KRX-TBM', name: 'Treatment & Booster Biocellullose Mask', category: 'Masques', price: 70.00, stockStatus: 'IN_STOCK', description: 'Masque biocellulose booster.' },
  { id: 'pre-extraction-softening-mask', sku: 'KRX-PESM', name: 'Pre Extraction Softening Mask - 220 g', category: 'Masques', price: 48.00, stockStatus: 'LOW_STOCK', description: 'Masque émollient avant extraction.' },
  { id: 'cryo-facial-icy-mask', sku: 'KRX-CFI', name: 'Cryofacial Icy Mask', category: 'Masques', price: 62.00, stockStatus: 'IN_STOCK', description: 'Masque effet cryo apaisant.' },
  { id: 'home-care-sheet-mask-cica', sku: 'KRX-HCSM-C', name: 'Home Care Sheet Mask (CICA)', category: 'Masques', price: 32.00, stockStatus: 'IN_STOCK', description: 'Masque apaisant Cica.' },
  { id: 'mud-to-sheet-mask', sku: 'KRX-MTS', name: 'Mud to Sheet Mask', category: 'Masques', price: 40.00, stockStatus: 'IN_STOCK', description: 'Masque boue purifiant en feuille.' },
  { id: 'home-care-sheet-mask-salicylic', sku: 'KRX-HCSM-S', name: 'Home Care Sheet Mask (Acide Salicylic)', category: 'Masques', price: 34.00, stockStatus: 'IN_STOCK', description: 'Masque purifiant acide salicylique.' },
  { id: 'v-tox-higher-power-lift-mask', sku: 'KRX-VTX', name: 'V-Tox Higher Power', category: 'Masques', price: 85.00, stockStatus: 'IN_STOCK', description: 'Masque effet lifting V-Shape.' },
  // --- MESOBOOSTER AMPOULE ---
  { id: 'meso-booster-ampoule-boto-rx', sku: 'KRX-MBA-BRX', name: 'Meso Booster Ampoule – Boto-RX', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Ampoule effet botox-like.' },
  { id: 'meso-booster-ampoule-ha', sku: 'KRX-MBA-HA', name: 'MesoBooster HA+', category: 'MesoBooster Ampoule', price: 105.00, stockStatus: 'IN_STOCK', description: 'Acide hyaluronique pur stérile.' },
  { id: 'meso-booster-ampoule-derm-acne-control', sku: 'KRX-MBA-DAC', name: 'Meso Booster Ampoule – Hydro Stemcell', category: 'MesoBooster Ampoule', price: 115.00, stockStatus: 'IN_STOCK', description: 'Cellules souches hydratantes.' },
  { id: 'premiun-ampoule-bio-placenta', sku: 'KRX-PABP', name: 'Premium Ampoule - Bio Placenta', category: 'MesoBooster Ampoule', price: 130.00, stockStatus: 'IN_STOCK', description: 'Facteurs de croissance bio-placenta.' },
  { id: 'ampoules-meso-booster-or-24k', sku: 'KRX-MBA-GOLD', name: 'Meso Booster Ampoule – Gold Peptide', category: 'MesoBooster Ampoule', price: 140.00, stockStatus: 'IN_STOCK', description: 'Peptides et or 24k.' },
  { id: 'premium-ampoule-ha-filling-powder', sku: 'KRX-PAHP', name: 'Premium Ampoule - HA Filling Powder', category: 'MesoBooster Ampoule', price: 125.00, stockStatus: 'IN_STOCK', description: 'Poudre HA comblante.' },
  { id: 'premium-ampoule-hair-meso-solution', sku: 'KRX-PAHM', name: 'Premium Ampoule - Hair Meso Solution', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Meso capillaire.' },
  { id: 'meso-booster-ampoule-salmon-dna-pdrn', sku: 'KRX-MBA-PDRN', name: 'Meso Booster Ampoule – Salmon DNA (PDRN)', category: 'MesoBooster Ampoule', price: 135.00, stockStatus: 'IN_STOCK', description: 'ADN de saumon régénérant.' },
  { id: 'ampoule-thread-filled', sku: 'KRX-ATF', name: 'Thread Fill Ampoule', category: 'MesoBooster Ampoule', price: 120.00, stockStatus: 'IN_STOCK', description: 'Ampoule effet fils tenseurs.' },
  { id: 'ampoule-undereye-solution', sku: 'KRX-AUES', name: 'Premium Ampoule - Undereye Solution', category: 'MesoBooster Ampoule', price: 95.00, stockStatus: 'IN_STOCK', description: 'Spécial contour des yeux.' },
  { id: 'meso-booster-ampoule-white-and-bright', sku: 'KRX-MBA-WB', name: 'Meso Booster Ampoule – White and Bright', category: 'MesoBooster Ampoule', price: 115.00, stockStatus: 'IN_STOCK', description: 'Complexe éclaircissant.' },
  { id: 'meso-booster-ampoule-derm-acne-control-1', sku: 'KRX-MBA-DAC1', name: 'Meso Booster Ampoule – Derm Acne Control', category: 'MesoBooster Ampoule', price: 110.00, stockStatus: 'IN_STOCK', description: 'Contrôle acné et sébum.' },
  // --- SÉRUM ---
  { id: 'gluthatione-solution', sku: 'KRX-GLU', name: 'Gluthatione Solution', category: 'Sérum', price: 75.00, stockStatus: 'LOW_STOCK', description: 'Solution éclat au glutathion.' },
  { id: 'hyal-plus-solution', sku: 'KRX-HPS', name: 'Hyal Plus Solution', category: 'Sérum', price: 72.00, stockStatus: 'LOW_STOCK', description: 'Booster hydratation intense.' },
  { id: 'mela-defense-serum', sku: 'KRX-MDS', name: 'Mela Defense Serum', category: 'Sérum', price: 89.00, stockStatus: 'IN_STOCK', description: 'Sérum anti-taches.' },
  { id: 'clinical-line-youthplex-face-lift-serum', sku: 'KRX-YFLS', name: 'Clinical Line Youthplex Face Lift Serum - 30 ml', category: 'Sérum', price: 110.00, stockStatus: 'OUT_OF_STOCK', description: 'Sérum liftant gamme clinique.' },
  { id: 'hair-boost-solution', sku: 'KRX-HBS', name: 'Hair Boost Solution', category: 'Sérum', price: 80.00, stockStatus: 'LOW_STOCK', description: 'Solution boost capillaire.' },
  { id: 'booster-set-4-solutions', sku: 'KRX-BS4', name: 'Booster Set 4 Solutions', category: 'Sérum', price: 250.00, stockStatus: 'LOW_STOCK', description: 'Kit complet 4 boosters.' },
  { id: 'all-day-glow-vitamin-serum', sku: 'KRX-ADGVS', name: 'All Day Glow Vitamin Serum', category: 'Sérum', price: 68.00, stockStatus: 'OUT_OF_STOCK', description: 'Sérum vitaminé éclat quotidien.' },
  { id: 'the-face-lift-intensive-firming-serum', sku: 'KRX-TFLS', name: 'The Face Lift Intensive Firming Serum', category: 'Sérum', price: 95.00, stockStatus: 'IN_STOCK', description: 'Sérum raffermissant intensif.' },
  { id: 'big-cica-recovery-serum-50ml', sku: 'KRX-BCRS', name: 'Big Cica Recovery Serum', category: 'Sérum', price: 78.00, stockStatus: 'LOW_STOCK', description: 'Grand format sérum Cica.' },
  { id: 'phytoxome-exosome-serum', sku: 'KRX-PES', name: 'PhytoXome', category: 'Sérum', price: 145.00, stockStatus: 'IN_STOCK', description: 'Sérum avancé aux exosomes.' },
  { id: 'sdna-repair-shot', sku: 'KRX-SRS', name: 'sDNA Repair Shot', category: 'Sérum', price: 85.00, stockStatus: 'LOW_STOCK', description: 'Shot réparateur ADN.' },
  // --- CRÈME ---
  { id: 'mela-defense-cream', sku: 'KRX-MDC', name: 'Mela Defense Cream - 50 g', category: 'Crème', price: 65.00, stockStatus: 'IN_STOCK', description: 'Crème correctrice pigmentation.' },
  { id: 'essence-cream-pad', sku: 'KRX-ECP', name: 'Essence Cream Pad', category: 'Crème', price: 45.00, stockStatus: 'IN_STOCK', description: 'Disques imprégnés de crème essence.' },
  { id: 'holiday-creme-neck-lift', sku: 'KRX-HNL', name: 'Holiday Crème Neck Lift (Édition Limitée)', category: 'Crème', price: 70.00, stockStatus: 'IN_STOCK', description: 'Crème cou liftante édition fêtes.' },
  { id: 'clinical-line-youthplex-face-lift-cream', sku: 'KRX-YFLC', name: 'Clinical Line Youthplex Face Lift Cream - 50 g', category: 'Crème', price: 98.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème liftante gamme clinique.' },
  { id: 'repair-cream', sku: 'KRX-RC', name: 'Repair Cream', category: 'Crème', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Crème réparatrice barrière cutanée.' },
  { id: 'neck-lift-intensive-firming-cream', sku: 'KRX-NLFC', name: 'Neck Lift Intensive Firming Cream', category: 'Crème', price: 75.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème raffermissante cou.' },
  { id: 'big-cica-recovery-all-day-cream', sku: 'KRX-BCRAC', name: 'Big Cica Recovery All Day Cream', category: 'Crème', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Crème jour récupération Cica.' },
  { id: 'strengthen-amp-protect-probiotic-cream', sku: 'KRX-SPPC', name: 'Strengthen Protect Probiotic Cream', category: 'Crème', price: 62.00, stockStatus: 'IN_STOCK', description: 'Crème probiotique protectrice.' },
  { id: 'all-day-glow-aqua-cream', sku: 'KRX-ADGAC', name: 'All Day Glow Aqua Cream', category: 'Crème', price: 55.00, stockStatus: 'IN_STOCK', description: 'Gel-crème hydratant éclat.' },
  { id: 'active-31-revitalizing-eye-cream', sku: 'KRX-A31', name: 'Active-31 Revitalizing Eye Cream', category: 'Crème', price: 52.00, stockStatus: 'LOW_STOCK', description: 'Crème yeux revitalisante.' },
  { id: 'cocoa-facial-massage-cream', sku: 'KRX-CFMC', name: 'Cocoa Facial Massage Cream', category: 'Crème', price: 48.00, stockStatus: 'OUT_OF_STOCK', description: 'Crème de massage au cacao.' },
  { id: 'clear-prevent-anti-acne-cream', sku: 'KRX-CPAC', name: 'Clear & Prevent Anti Acne Cream', category: 'Crème', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Crème traitante anti-acné.' },
  // --- TONIQUE ---
  { id: 'clear-prevent-anti-acne-face-toner', sku: 'KRX-CPAT', name: 'Clear & Prevent Anti Acne Face Toner', category: 'Tonique', price: 38.00, stockStatus: 'LOW_STOCK', description: 'Tonique purifiant acné.' },
  { id: 'big-cica-recovery-ultra-healing-toner', sku: 'KRX-BCRT', name: 'Big Cica Recovery Ultra Healing Toner', category: 'Tonique', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Tonique réparateur grand format.' },
  { id: 'strengthen-protect-probiotic-toner', sku: 'KRX-SPPT', name: 'Strengthen & Protect Probiotic Toner', category: 'Tonique', price: 40.00, stockStatus: 'LOW_STOCK', description: 'Tonique équilibrant probiotique.' },
  { id: 'clinical-line-youthplex-toner', sku: 'KRX-YPT', name: 'Clinical Line Youthplex Face Lift Toning Solution', category: 'Tonique', price: 55.00, stockStatus: 'OUT_OF_STOCK', description: 'Lotion tonique liftante.' },
  { id: 'quenching-toner-all-day-glow', sku: 'KRX-QTADG', name: 'Quenching Toner All Day Glow', category: 'Tonique', price: 38.00, stockStatus: 'IN_STOCK', description: 'Tonique hydratant éclat.' },
  { id: 'biocell-bc3-cica', sku: 'KRX-BC3', name: 'BioCell+ BC3 "Cica" - 300 ml', category: 'Tonique', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Solution tonique apaisante Cica.' },
  { id: 'biocell-ha-collagen', sku: 'KRX-BC2', name: 'BioCell+ BC2 "HA & Collagen" - 300 ml', category: 'Tonique', price: 58.00, stockStatus: 'LOW_STOCK', description: 'Solution tonique hydratante collagène.' },
  // --- DÉMAQUILLANT - NETTOYANT ---
  { id: 'oxy-glow-bubble-cleanser-spiulina-tiny-pumpple', sku: 'KRX-OGBC', name: 'Oxy Glow Bubble Cleanser "Pumpkin + Blue Tansy + Spirulina"', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant moussant oxygénant.' },
  { id: 'clinical-line-youthplex-cleanser', sku: 'KRX-YPC', name: 'Clinical Line Youthplex Face Lift Cleansing Fluid', category: 'Démaquillant - Nettoyant', price: 48.00, stockStatus: 'OUT_OF_STOCK', description: 'Fluide nettoyant liftant.' },
  { id: 'gel-cleanser-all-day-glow', sku: 'KRX-GCADG', name: 'Gel Cleanser All Day Glow', category: 'Démaquillant - Nettoyant', price: 32.00, stockStatus: 'IN_STOCK', description: 'Gel nettoyant éclat.' },
  { id: 'lait-demaquillant', sku: 'KRX-LDNE', name: 'Lait Démaquillant Nettoyant Enzymatique - 1000 ml', category: 'Démaquillant - Nettoyant', price: 85.00, stockStatus: 'OUT_OF_STOCK', description: 'Lait nettoyant format cabine.' },
  { id: 'lait-demaquillant-nettoyant-enzymatique-antibacterien-1000-ml', sku: 'KRX-LDNEA', name: 'Lait Démaquillant Nettoyant Enzymatique & Antibactérien - 1000 ml', category: 'Démaquillant - Nettoyant', price: 90.00, stockStatus: 'OUT_OF_STOCK', description: 'Lait antibactérien cabine.' },
  { id: 'cica-recovery-2-in-1-mask-cleanser-1', sku: 'KRX-CR21', name: 'Cica Recovery 2 in 1 Mask Cleanser', category: 'Démaquillant - Nettoyant', price: 42.00, stockStatus: 'OUT_OF_STOCK', description: 'Nettoyant et masque apaisant.' },
  { id: 'oxy-glow-bubble-wash-spirulina', sku: 'KRX-OGBS', name: 'Oxy Glow Bubble Cleanser Spirulina - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant spiruline.' },
  { id: 'oxy-glow-bubble-wash-blue-tansy', sku: 'KRX-OGBB', name: 'Oxy Glow Bubble Cleanser Blue Tansy - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant tanaisie bleue.' },
  { id: 'oxy-glow-bubble-wash-pumpkin', sku: 'KRX-OGBP', name: 'Oxy Glow Bubble Cleanser Pumpkin - 150 ml', category: 'Démaquillant - Nettoyant', price: 35.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant citrouille.' },
  { id: 'clear-prevent-anti-acne-face-wash', sku: 'KRX-CPAW', name: 'Clear & Prevent Anti Acne Face Wash', category: 'Démaquillant - Nettoyant', price: 30.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant visage anti-acné.' },
  { id: 'strengthen-protect-probiotic-face-wash', sku: 'KRX-SPPW', name: 'Strengthen & Protect Probiotic Face Wash', category: 'Démaquillant - Nettoyant', price: 34.00, stockStatus: 'LOW_STOCK', description: 'Nettoyant visage probiotique.' },
  { id: 'lait-nettoyant-enzymatique-antibacterien-250-ml', sku: 'KRX-LNEA-250', name: 'Lait Démaquillant Nettoyant Enzymatique - 250 ml', category: 'Démaquillant - Nettoyant', price: 38.00, stockStatus: 'IN_STOCK', description: 'Lait nettoyant revente.' },
  { id: 'lait-nettoyant-enzymatique-antibacterien-1000-ml-2', sku: 'KRX-LNEA-250-AB', name: 'Lait Démaquillant Nettoyant Enzymatique & Antibactérien - 250 ml', category: 'Démaquillant - Nettoyant', price: 40.00, stockStatus: 'IN_STOCK', description: 'Lait antibactérien revente.' },
  { id: 'huile-nettoyante-demaquillante', sku: 'KRX-HND', name: 'Pre Cleansing Oil', category: 'Démaquillant - Nettoyant', price: 45.00, stockStatus: 'LOW_STOCK', description: 'Huile démaquillante.' },
  // --- TRAITEMENT SPÉCIALISÉ ---
  { id: 'carboxy-therapy-co2-500ml', sku: 'KRX-CT500', name: 'Carboxy Therapy CO2 - 500 ml', category: 'Traitement Spécialisé', price: 160.00, stockStatus: 'LOW_STOCK', description: 'Gel carboxythérapie format pro.' },
  { id: 'carboxy-therapy-co2-1000ml', sku: 'KRX-CT1000', name: 'Carboxy Therapy CO2 - 1000ml', category: 'Traitement Spécialisé', price: 290.00, stockStatus: 'OUT_OF_STOCK', description: 'Gel carboxythérapie format maxi.' },
  { id: 'inflacure-healing-active', sku: 'KRX-IHA', name: 'Inflacure Healing Active', category: 'Traitement Spécialisé', price: 85.00, stockStatus: 'IN_STOCK', description: 'Traitement actif anti-inflammatoire.' },
  { id: 'pd-13-therapy', sku: 'KRX-PD13', name: 'PD-13 Therapy', category: 'Traitement Spécialisé', price: 140.00, stockStatus: 'LOW_STOCK', description: 'Thérapie photodynamique.' },
  { id: 'carboxy-therapy-co-mini-150-ml', sku: 'KRX-CT150', name: 'Carboxy Therapy CO₂ Mini – 150 ml', category: 'Traitement Spécialisé', price: 65.00, stockStatus: 'LOW_STOCK', description: 'Kit essai carboxythérapie.' },
  { id: 'ze-tox', sku: 'KRX-ZTX', name: 'ZE-TOX', category: 'Traitement Spécialisé', price: 120.00, stockStatus: 'IN_STOCK', description: 'Traitement détoxifiant avancé.' },
  { id: 'vitaamedi', sku: 'KRX-VTM', name: 'VITAMEDI Solution', category: 'Traitement Spécialisé', price: 95.00, stockStatus: 'IN_STOCK', description: 'Solution vitaminée médi-esthétique.' },
  // --- SOLUTION HYDRAFACIAL ---
  { id: 'solution-hydrafacial-3-x', sku: 'KRX-SH3', name: 'Solutions BioCell+ "BC1/BC2/BC3" - Pack 3 x 300 ml', category: 'Solution HydraFacial', price: 150.00, stockStatus: 'LOW_STOCK', description: 'Pack complet solutions hydrodermabrasion.' },
  { id: 'hydraskin', sku: 'KRX-HDS', name: 'HydraSkin', category: 'Solution HydraFacial', price: 55.00, stockStatus: 'OUT_OF_STOCK', description: 'Solution hydratante pour machine.' },
  // --- GAMME HOMECARE ---
  { id: 'holiday-pack-acne-edition-limitee', sku: 'KRX-HP-ACNE', name: 'Holiday Set Acné Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes anti-acné.' },
  { id: 'holiday-pack-glow-edition-limitee', sku: 'KRX-HP-GLOW', name: 'Holiday Set Glow Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes éclat.' },
  { id: 'holiday-pack-probiotic-edition-limitee', sku: 'KRX-HP-PROBIO', name: 'Holiday Set Probiotic Line (Édition Limitée)', category: 'Gamme HomeCare', price: 85.00, stockStatus: 'IN_STOCK', description: 'Coffret fêtes probiotiques.' },
  { id: 'gamme-complete-strenghten-protect-probiotic', sku: 'KRX-GC-SPP', name: 'Gamme Complète Strenghten & Protect Probiotic', category: 'Gamme HomeCare', price: 180.00, stockStatus: 'LOW_STOCK', description: 'Routine complète probiotique.' },
  { id: 'gamme-complete-clear-prevent-anti-acne', sku: 'KRX-GC-CPA', name: 'Gamme Complète Clear & Prevent Anti Acné', category: 'Gamme HomeCare', price: 175.00, stockStatus: 'LOW_STOCK', description: 'Routine complète acné.' },
  { id: 'gamme-complete-all-day-glow', sku: 'KRX-GC-ADG', name: 'Gamme Complète All Day Glow', category: 'Gamme HomeCare', price: 190.00, stockStatus: 'OUT_OF_STOCK', description: 'Routine complète éclat.' },
  { id: 'gamme-complete-clinical-line-youthplex-face-lift', sku: 'KRX-GC-YFL', name: 'Gamme Clinical Line Youthplex Face Lift', category: 'Gamme HomeCare', price: 250.00, stockStatus: 'OUT_OF_STOCK', description: 'Routine complète lifting.' },
  { id: 'clinical-skin-filler-tinted-sunscreen-light-medium', sku: 'KRX-CSF-LM', name: 'Clinical Skin Filler Tinted Sunscreen (Light-Medium)', category: 'Gamme HomeCare', price: 58.00, stockStatus: 'IN_STOCK', description: 'Protection solaire teintée claire.' },
  { id: 'clinical-skin-filler-tinted-sunscreen-medium-dark', sku: 'KRX-CSF-MD', name: 'Clinical Skin Filler Tinted Sunscreen (Medium-Dark)', category: 'Gamme HomeCare', price: 58.00, stockStatus: 'IN_STOCK', description: 'Protection solaire teintée foncée.' },
  { id: 'all-day-glow-sunblocker-spf-50', sku: 'KRX-ADGS', name: 'All Day Glow Sunblocker SPF 50', category: 'Gamme HomeCare', price: 48.00, stockStatus: 'IN_STOCK', description: 'Protection solaire SPF 50 éclat.' },
  { id: 'trial-package-kit-booster', sku: 'KRX-TPKB', name: 'Trial Package Kit Booster', category: 'Gamme HomeCare', price: 45.00, stockStatus: 'IN_STOCK', description: 'Kit découverte boosters.' },
  { id: 'cica-recovery-set', sku: 'KRX-CRS', name: 'Cica Recovery Set', category: 'Gamme HomeCare', price: 95.00, stockStatus: 'LOW_STOCK', description: 'Set récupération Cica.' },
  { id: 'jelly-mist', sku: 'KRX-JM', name: 'Jelly Mist', category: 'Gamme HomeCare', price: 35.00, stockStatus: 'IN_STOCK', description: 'Brume hydratante gélifiée.' },
  { id: 'patch-microneedling-cernes', sku: 'KRX-PMC', name: 'Patch Microneedling Cernes', category: 'Gamme HomeCare', price: 25.00, stockStatus: 'IN_STOCK', description: 'Patchs yeux micro-aiguilles.' },
  { id: 'patch-microneedling-levres', sku: 'KRX-PML', name: 'Patch Microneedling Lèvres', category: 'Gamme HomeCare', price: 25.00, stockStatus: 'IN_STOCK', description: 'Patchs lèvres micro-aiguilles.' },
  // --- EXFOLIANT ---
  { id: 'cacao-facial-powder-wash', sku: 'KRX-CFPW', name: 'Cocoa Facial Powder Wash - 100 g', category: 'Exfoliant', price: 42.00, stockStatus: 'LOW_STOCK', description: 'Poudre nettoyante enzymatique cacao.' },
  { id: 'skin-prep-exfoliant-solution', sku: 'KRX-SPES', name: 'Skin Prep Exfoliant Solution - 150 ml', category: 'Exfoliant', price: 38.00, stockStatus: 'IN_STOCK', description: 'Solution exfoliante preparatoire.' },
  // --- ACCESSOIRE ---
  { id: 'pinceau-krx-silicone', sku: 'KRX-ACC-SIL', name: 'Pinceau Silicone KRX', category: 'Accessoire', price: 15.00, stockStatus: 'OUT_OF_STOCK', description: 'Pinceau application silicone.' },
  { id: 'pinceau-krx-eventail', sku: 'KRX-ACC-FAN', name: 'Pinceau Eventail KRX', category: 'Accessoire', price: 18.00, stockStatus: 'OUT_OF_STOCK', description: 'Pinceau éventail poils doux.' },
  { id: 'bandeau-krx', sku: 'KRX-ACC-HB', name: 'Bandeau KRX', category: 'Accessoire', price: 12.00, stockStatus: 'OUT_OF_STOCK', description: 'Bandeau soin visage.' },
];

export const PRODUCTS: Product[] = RAW_PRODUCTS.map(withPricing);

export const ACADEMY_CONTENT: AcademyResource[] = [
  { id: 'a1', title: 'Green Sea Peel: Protocoles Fondamentaux', type: 'PDF', category: 'Protocole', tierReq: UserTier.STANDARD, status: 'PUBLISHED', thumbnail: 'https://picsum.photos/400/300?grayscale', duration: '14 pages' },
  { id: 'a2', title: 'Carboxy Therapy: Application Professionnelle', type: 'VIDEO', category: 'Traitement', tierReq: UserTier.STANDARD, status: 'PUBLISHED', thumbnail: 'https://picsum.photos/400/301?grayscale', duration: '12 min' },
  { id: 'a3', title: 'Masterclass: Gestion de l\'Hyperpigmentation', type: 'VIDEO', category: 'Advanced', tierReq: UserTier.PREMIUM_BASE, status: 'PUBLISHED', thumbnail: 'https://picsum.photos/400/302?grayscale', duration: '45 min' },
  { id: 'a4', title: 'Certification Avancée: Anti-Âge Cellulaire', type: 'CERTIFICATION', category: 'Elite', tierReq: UserTier.PREMIUM_BASE, status: 'PUBLISHED', thumbnail: 'https://picsum.photos/400/303?grayscale', duration: 'Examen' },
];