-- MODIFICAR TABLA DE PEDIDOS PARA AGREGAR NUEVAS COLUMNAS
ALTER TABLE public.orders 
ADD COLUMN IF NOT EXISTS channel TEXT DEFAULT 'Online Store',
ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'Pagado',
ADD COLUMN IF NOT EXISTS delivery_status TEXT DEFAULT 'En attente',
ADD COLUMN IF NOT EXISTS delivery_method TEXT DEFAULT 'Livraison standard',
ADD COLUMN IF NOT EXISTS tags JSONB DEFAULT '[]'::jsonb;
